// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/org/v2/org.proto (package zitadel.org.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Details } from "../../object/v2/object_pb";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/org/v2/org.proto.
 */
export const file_zitadel_org_v2_org: GenFile = /*@__PURE__*/
  fileDesc("Chh6aXRhZGVsL29yZy92Mi9vcmcucHJvdG8SDnppdGFkZWwub3JnLnYyIp8BCgxPcmdhbml6YXRpb24SCgoCaWQYASABKAkSKwoHZGV0YWlscxgCIAEoCzIaLnppdGFkZWwub2JqZWN0LnYyLkRldGFpbHMSMAoFc3RhdGUYAyABKA4yIS56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25TdGF0ZRIMCgRuYW1lGAQgASgJEhYKDnByaW1hcnlfZG9tYWluGAUgASgJIpkBCgZEb21haW4SFwoPb3JnYW5pemF0aW9uX2lkGAEgASgJEg4KBmRvbWFpbhgCIAEoCRITCgtpc192ZXJpZmllZBgDIAEoCBISCgppc19wcmltYXJ5GAQgASgIEj0KD3ZhbGlkYXRpb25fdHlwZRgFIAEoDjIkLnppdGFkZWwub3JnLnYyLkRvbWFpblZhbGlkYXRpb25UeXBlKpcBChFPcmdhbml6YXRpb25TdGF0ZRIiCh5PUkdBTklaQVRJT05fU1RBVEVfVU5TUEVDSUZJRUQQABIdChlPUkdBTklaQVRJT05fU1RBVEVfQUNUSVZFEAESHwobT1JHQU5JWkFUSU9OX1NUQVRFX0lOQUNUSVZFEAISHgoaT1JHQU5JWkFUSU9OX1NUQVRFX1JFTU9WRUQQAyp/ChREb21haW5WYWxpZGF0aW9uVHlwZRImCiJET01BSU5fVkFMSURBVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASHwobRE9NQUlOX1ZBTElEQVRJT05fVFlQRV9IVFRQEAESHgoaRE9NQUlOX1ZBTElEQVRJT05fVFlQRV9ETlMQAmIGcHJvdG8z", [file_google_protobuf_timestamp, file_zitadel_object_v2_object]);

/**
 * @generated from message zitadel.org.v2.Organization
 */
export type Organization = Message<"zitadel.org.v2.Organization"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: zitadel.object.v2.Details details = 2;
   */
  details?: Details | undefined;

  /**
   * @generated from field: zitadel.org.v2.OrganizationState state = 3;
   */
  state: OrganizationState;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string primary_domain = 5;
   */
  primaryDomain: string;
};

/**
 * Describes the message zitadel.org.v2.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export const OrganizationSchema: GenMessage<Organization> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_org, 0);

/**
 * @generated from message zitadel.org.v2.Domain
 */
export type Domain = Message<"zitadel.org.v2.Domain"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: string domain = 2;
   */
  domain: string;

  /**
   * @generated from field: bool is_verified = 3;
   */
  isVerified: boolean;

  /**
   * @generated from field: bool is_primary = 4;
   */
  isPrimary: boolean;

  /**
   * @generated from field: zitadel.org.v2.DomainValidationType validation_type = 5;
   */
  validationType: DomainValidationType;
};

/**
 * Describes the message zitadel.org.v2.Domain.
 * Use `create(DomainSchema)` to create a new message.
 */
export const DomainSchema: GenMessage<Domain> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_org, 1);

/**
 * @generated from enum zitadel.org.v2.OrganizationState
 */
export enum OrganizationState {
  /**
   * @generated from enum value: ORGANIZATION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORGANIZATION_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: ORGANIZATION_STATE_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: ORGANIZATION_STATE_REMOVED = 3;
   */
  REMOVED = 3,
}

/**
 * Describes the enum zitadel.org.v2.OrganizationState.
 */
export const OrganizationStateSchema: GenEnum<OrganizationState> = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_org, 0);

/**
 * @generated from enum zitadel.org.v2.DomainValidationType
 */
export enum DomainValidationType {
  /**
   * @generated from enum value: DOMAIN_VALIDATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DOMAIN_VALIDATION_TYPE_HTTP = 1;
   */
  HTTP = 1,

  /**
   * @generated from enum value: DOMAIN_VALIDATION_TYPE_DNS = 2;
   */
  DNS = 2,
}

/**
 * Describes the enum zitadel.org.v2.DomainValidationType.
 */
export const DomainValidationTypeSchema: GenEnum<DomainValidationType> = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_org, 1);

