// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/org/v2/query.proto (package zitadel.org.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { OrganizationState } from "./org_pb";
import { file_zitadel_org_v2_org } from "./org_pb";
import type { TextQueryMethod } from "../../object/v2/object_pb";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/org/v2/query.proto.
 */
export const file_zitadel_org_v2_query: GenFile = /*@__PURE__*/
  fileDesc("Chp6aXRhZGVsL29yZy92Mi9xdWVyeS5wcm90bxIOeml0YWRlbC5vcmcudjIizwIKC1NlYXJjaFF1ZXJ5EjsKCm5hbWVfcXVlcnkYASABKAsyJS56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25OYW1lUXVlcnlIABI/Cgxkb21haW5fcXVlcnkYAiABKAsyJy56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25Eb21haW5RdWVyeUgAEj0KC3N0YXRlX3F1ZXJ5GAMgASgLMiYueml0YWRlbC5vcmcudjIuT3JnYW5pemF0aW9uU3RhdGVRdWVyeUgAEjcKCGlkX3F1ZXJ5GAQgASgLMiMueml0YWRlbC5vcmcudjIuT3JnYW5pemF0aW9uSURRdWVyeUgAEkEKDWRlZmF1bHRfcXVlcnkYBSABKAsyKC56aXRhZGVsLm9yZy52Mi5EZWZhdWx0T3JnYW5pemF0aW9uUXVlcnlIAEIHCgVxdWVyeSJZChVPcmdhbml6YXRpb25OYW1lUXVlcnkSDAoEbmFtZRgBIAEoCRIyCgZtZXRob2QYAiABKA4yIi56aXRhZGVsLm9iamVjdC52Mi5UZXh0UXVlcnlNZXRob2QiXQoXT3JnYW5pemF0aW9uRG9tYWluUXVlcnkSDgoGZG9tYWluGAEgASgJEjIKBm1ldGhvZBgCIAEoDjIiLnppdGFkZWwub2JqZWN0LnYyLlRleHRRdWVyeU1ldGhvZCJKChZPcmdhbml6YXRpb25TdGF0ZVF1ZXJ5EjAKBXN0YXRlGAEgASgOMiEueml0YWRlbC5vcmcudjIuT3JnYW5pemF0aW9uU3RhdGUiIQoTT3JnYW5pemF0aW9uSURRdWVyeRIKCgJpZBgBIAEoCSIaChhEZWZhdWx0T3JnYW5pemF0aW9uUXVlcnkiYAoSRG9tYWluU2VhcmNoRmlsdGVyEkAKDWRvbWFpbl9maWx0ZXIYASABKAsyJy56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25Eb21haW5RdWVyeUgAQggKBmZpbHRlciqNAQoVT3JnYW5pemF0aW9uRmllbGROYW1lEicKI09SR0FOSVpBVElPTl9GSUVMRF9OQU1FX1VOU1BFQ0lGSUVEEAASIAocT1JHQU5JWkFUSU9OX0ZJRUxEX05BTUVfTkFNRRABEikKJU9SR0FOSVpBVElPTl9GSUVMRF9OQU1FX0NSRUFUSU9OX0RBVEUQAip1Cg9Eb21haW5GaWVsZE5hbWUSIQodRE9NQUlOX0ZJRUxEX05BTUVfVU5TUEVDSUZJRUQQABIaChZET01BSU5fRklFTERfTkFNRV9OQU1FEAESIwofRE9NQUlOX0ZJRUxEX05BTUVfQ1JFQVRJT05fREFURRACYgZwcm90bzM", [file_zitadel_org_v2_org, file_zitadel_object_v2_object]);

/**
 * @generated from message zitadel.org.v2.SearchQuery
 */
export type SearchQuery = Message<"zitadel.org.v2.SearchQuery"> & {
  /**
   * @generated from oneof zitadel.org.v2.SearchQuery.query
   */
  query: {
    /**
     * @generated from field: zitadel.org.v2.OrganizationNameQuery name_query = 1;
     */
    value: OrganizationNameQuery;
    case: "nameQuery";
  } | {
    /**
     * @generated from field: zitadel.org.v2.OrganizationDomainQuery domain_query = 2;
     */
    value: OrganizationDomainQuery;
    case: "domainQuery";
  } | {
    /**
     * @generated from field: zitadel.org.v2.OrganizationStateQuery state_query = 3;
     */
    value: OrganizationStateQuery;
    case: "stateQuery";
  } | {
    /**
     * @generated from field: zitadel.org.v2.OrganizationIDQuery id_query = 4;
     */
    value: OrganizationIDQuery;
    case: "idQuery";
  } | {
    /**
     * @generated from field: zitadel.org.v2.DefaultOrganizationQuery default_query = 5;
     */
    value: DefaultOrganizationQuery;
    case: "defaultQuery";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.org.v2.SearchQuery.
 * Use `create(SearchQuerySchema)` to create a new message.
 */
export const SearchQuerySchema: GenMessage<SearchQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 0);

/**
 * @generated from message zitadel.org.v2.OrganizationNameQuery
 */
export type OrganizationNameQuery = Message<"zitadel.org.v2.OrganizationNameQuery"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: zitadel.object.v2.TextQueryMethod method = 2;
   */
  method: TextQueryMethod;
};

/**
 * Describes the message zitadel.org.v2.OrganizationNameQuery.
 * Use `create(OrganizationNameQuerySchema)` to create a new message.
 */
export const OrganizationNameQuerySchema: GenMessage<OrganizationNameQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 1);

/**
 * @generated from message zitadel.org.v2.OrganizationDomainQuery
 */
export type OrganizationDomainQuery = Message<"zitadel.org.v2.OrganizationDomainQuery"> & {
  /**
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * @generated from field: zitadel.object.v2.TextQueryMethod method = 2;
   */
  method: TextQueryMethod;
};

/**
 * Describes the message zitadel.org.v2.OrganizationDomainQuery.
 * Use `create(OrganizationDomainQuerySchema)` to create a new message.
 */
export const OrganizationDomainQuerySchema: GenMessage<OrganizationDomainQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 2);

/**
 * @generated from message zitadel.org.v2.OrganizationStateQuery
 */
export type OrganizationStateQuery = Message<"zitadel.org.v2.OrganizationStateQuery"> & {
  /**
   * @generated from field: zitadel.org.v2.OrganizationState state = 1;
   */
  state: OrganizationState;
};

/**
 * Describes the message zitadel.org.v2.OrganizationStateQuery.
 * Use `create(OrganizationStateQuerySchema)` to create a new message.
 */
export const OrganizationStateQuerySchema: GenMessage<OrganizationStateQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 3);

/**
 * @generated from message zitadel.org.v2.OrganizationIDQuery
 */
export type OrganizationIDQuery = Message<"zitadel.org.v2.OrganizationIDQuery"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zitadel.org.v2.OrganizationIDQuery.
 * Use `create(OrganizationIDQuerySchema)` to create a new message.
 */
export const OrganizationIDQuerySchema: GenMessage<OrganizationIDQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 4);

/**
 * @generated from message zitadel.org.v2.DefaultOrganizationQuery
 */
export type DefaultOrganizationQuery = Message<"zitadel.org.v2.DefaultOrganizationQuery"> & {
};

/**
 * Describes the message zitadel.org.v2.DefaultOrganizationQuery.
 * Use `create(DefaultOrganizationQuerySchema)` to create a new message.
 */
export const DefaultOrganizationQuerySchema: GenMessage<DefaultOrganizationQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 5);

/**
 * @generated from message zitadel.org.v2.DomainSearchFilter
 */
export type DomainSearchFilter = Message<"zitadel.org.v2.DomainSearchFilter"> & {
  /**
   * @generated from oneof zitadel.org.v2.DomainSearchFilter.filter
   */
  filter: {
    /**
     * @generated from field: zitadel.org.v2.OrganizationDomainQuery domain_filter = 1;
     */
    value: OrganizationDomainQuery;
    case: "domainFilter";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.org.v2.DomainSearchFilter.
 * Use `create(DomainSearchFilterSchema)` to create a new message.
 */
export const DomainSearchFilterSchema: GenMessage<DomainSearchFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 6);

/**
 * @generated from enum zitadel.org.v2.OrganizationFieldName
 */
export enum OrganizationFieldName {
  /**
   * @generated from enum value: ORGANIZATION_FIELD_NAME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORGANIZATION_FIELD_NAME_NAME = 1;
   */
  NAME = 1,

  /**
   * @generated from enum value: ORGANIZATION_FIELD_NAME_CREATION_DATE = 2;
   */
  CREATION_DATE = 2,
}

/**
 * Describes the enum zitadel.org.v2.OrganizationFieldName.
 */
export const OrganizationFieldNameSchema: GenEnum<OrganizationFieldName> = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_query, 0);

/**
 * @generated from enum zitadel.org.v2.DomainFieldName
 */
export enum DomainFieldName {
  /**
   * @generated from enum value: DOMAIN_FIELD_NAME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DOMAIN_FIELD_NAME_NAME = 1;
   */
  NAME = 1,

  /**
   * @generated from enum value: DOMAIN_FIELD_NAME_CREATION_DATE = 2;
   */
  CREATION_DATE = 2,
}

/**
 * Describes the enum zitadel.org.v2.DomainFieldName.
 */
export const DomainFieldNameSchema: GenEnum<DomainFieldName> = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_query, 1);

