export const DOCS_TAGS = {
	SETTINGS: "Settings",
	LOGIN_NAME: "Login Name",
	ACCOUNTS: "Accounts",
	PASSWORD: "Password",
	PASSKEY: "Passkey",
	U2F: "U2F",
	OTP: "OTP",
	MFA: "MFA",
	AUTHENTICATOR: "Authenticator",
	SESSION: "Session",
	FLOW: "Flow",
	REGISTER: "Register",
	VERIFY: "Verify",
	SIGNED_IN: "Signed In",
	LOGOUT: "Logout",
	DEVICE: "Device",
	IDP: "Identity Providers",
} as const;
