// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/saml/v2/authorization.proto (package zitadel.saml.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/saml/v2/authorization.proto.
 */
export const file_zitadel_saml_v2_authorization: GenFile = /*@__PURE__*/
  fileDesc("CiN6aXRhZGVsL3NhbWwvdjIvYXV0aG9yaXphdGlvbi5wcm90bxIPeml0YWRlbC5zYW1sLnYyIqYBCgtTQU1MUmVxdWVzdBIKCgJpZBgBIAEoCRIxCg1jcmVhdGlvbl9kYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZpc3N1ZXIYAyABKAkSIgoaYXNzZXJ0aW9uX2NvbnN1bWVyX3NlcnZpY2UYBCABKAkSEwoLcmVsYXlfc3RhdGUYBSABKAkSDwoHYmluZGluZxgGIAEoCSJ3ChJBdXRob3JpemF0aW9uRXJyb3ISKwoFZXJyb3IYASABKA4yHC56aXRhZGVsLnNhbWwudjIuRXJyb3JSZWFzb24SHgoRZXJyb3JfZGVzY3JpcHRpb24YAiABKAlIAIgBAUIUChJfZXJyb3JfZGVzY3JpcHRpb24qsQIKC0Vycm9yUmVhc29uEhwKGEVSUk9SX1JFQVNPTl9VTlNQRUNJRklFRBAAEiIKHkVSUk9SX1JFQVNPTl9WRVJTSU9OX01JU1NNQVRDSBABEh4KGkVSUk9SX1JFQVNPTl9BVVRIX05fRkFJTEVEEAISKwonRVJST1JfUkVBU09OX0lOVkFMSURfQVRUUl9OQU1FX09SX1ZBTFVFEAMSJgoiRVJST1JfUkVBU09OX0lOVkFMSURfTkFNRUlEX1BPTElDWRAEEh8KG0VSUk9SX1JFQVNPTl9SRVFVRVNUX0RFTklFRBAFEiQKIEVSUk9SX1JFQVNPTl9SRVFVRVNUX1VOU1VQUE9SVEVEEAYSJAogRVJST1JfUkVBU09OX1VOU1VQUE9SVEVEX0JJTkRJTkcQB2IGcHJvdG8z", [file_google_protobuf_duration, file_google_protobuf_timestamp]);

/**
 * @generated from message zitadel.saml.v2.SAMLRequest
 */
export type SAMLRequest = Message<"zitadel.saml.v2.SAMLRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp | undefined;

  /**
   * @generated from field: string issuer = 3;
   */
  issuer: string;

  /**
   * @generated from field: string assertion_consumer_service = 4;
   */
  assertionConsumerService: string;

  /**
   * @generated from field: string relay_state = 5;
   */
  relayState: string;

  /**
   * @generated from field: string binding = 6;
   */
  binding: string;
};

/**
 * Describes the message zitadel.saml.v2.SAMLRequest.
 * Use `create(SAMLRequestSchema)` to create a new message.
 */
export const SAMLRequestSchema: GenMessage<SAMLRequest> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_authorization, 0);

/**
 * @generated from message zitadel.saml.v2.AuthorizationError
 */
export type AuthorizationError = Message<"zitadel.saml.v2.AuthorizationError"> & {
  /**
   * @generated from field: zitadel.saml.v2.ErrorReason error = 1;
   */
  error: ErrorReason;

  /**
   * @generated from field: optional string error_description = 2;
   */
  errorDescription?: string | undefined;
};

/**
 * Describes the message zitadel.saml.v2.AuthorizationError.
 * Use `create(AuthorizationErrorSchema)` to create a new message.
 */
export const AuthorizationErrorSchema: GenMessage<AuthorizationError> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_authorization, 1);

/**
 * @generated from enum zitadel.saml.v2.ErrorReason
 */
export enum ErrorReason {
  /**
   * @generated from enum value: ERROR_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_REASON_VERSION_MISSMATCH = 1;
   */
  VERSION_MISSMATCH = 1,

  /**
   * @generated from enum value: ERROR_REASON_AUTH_N_FAILED = 2;
   */
  AUTH_N_FAILED = 2,

  /**
   * @generated from enum value: ERROR_REASON_INVALID_ATTR_NAME_OR_VALUE = 3;
   */
  INVALID_ATTR_NAME_OR_VALUE = 3,

  /**
   * @generated from enum value: ERROR_REASON_INVALID_NAMEID_POLICY = 4;
   */
  INVALID_NAMEID_POLICY = 4,

  /**
   * @generated from enum value: ERROR_REASON_REQUEST_DENIED = 5;
   */
  REQUEST_DENIED = 5,

  /**
   * @generated from enum value: ERROR_REASON_REQUEST_UNSUPPORTED = 6;
   */
  REQUEST_UNSUPPORTED = 6,

  /**
   * @generated from enum value: ERROR_REASON_UNSUPPORTED_BINDING = 7;
   */
  UNSUPPORTED_BINDING = 7,
}

/**
 * Describes the enum zitadel.saml.v2.ErrorReason.
 */
export const ErrorReasonSchema: GenEnum<ErrorReason> = /*@__PURE__*/
  enumDesc(file_zitadel_saml_v2_authorization, 0);

