// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/saml/v2/saml_service.proto (package zitadel.saml.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Details } from "../../object/v2/object_pb";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb";
import type { AuthorizationError, SAMLRequest } from "./authorization_pb";
import { file_zitadel_saml_v2_authorization } from "./authorization_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/saml/v2/saml_service.proto.
 */
export const file_zitadel_saml_v2_saml_service: GenFile = /*@__PURE__*/
  fileDesc("CiJ6aXRhZGVsL3NhbWwvdjIvc2FtbF9zZXJ2aWNlLnByb3RvEg96aXRhZGVsLnNhbWwudjIiMAoVR2V0U0FNTFJlcXVlc3RSZXF1ZXN0EhcKD3NhbWxfcmVxdWVzdF9pZBgBIAEoCSJMChZHZXRTQU1MUmVxdWVzdFJlc3BvbnNlEjIKDHNhbWxfcmVxdWVzdBgBIAEoCzIcLnppdGFkZWwuc2FtbC52Mi5TQU1MUmVxdWVzdCKkAQoVQ3JlYXRlUmVzcG9uc2VSZXF1ZXN0EhcKD3NhbWxfcmVxdWVzdF9pZBgBIAEoCRIrCgdzZXNzaW9uGAIgASgLMhgueml0YWRlbC5zYW1sLnYyLlNlc3Npb25IABI0CgVlcnJvchgDIAEoCzIjLnppdGFkZWwuc2FtbC52Mi5BdXRob3JpemF0aW9uRXJyb3JIAEIPCg1yZXNwb25zZV9raW5kIjQKB1Nlc3Npb24SEgoKc2Vzc2lvbl9pZBgBIAEoCRIVCg1zZXNzaW9uX3Rva2VuGAIgASgJIsMBChZDcmVhdGVSZXNwb25zZVJlc3BvbnNlEisKB2RldGFpbHMYASABKAsyGi56aXRhZGVsLm9iamVjdC52Mi5EZXRhaWxzEgsKA3VybBgCIAEoCRI1CghyZWRpcmVjdBgDIAEoCzIhLnppdGFkZWwuc2FtbC52Mi5SZWRpcmVjdFJlc3BvbnNlSAASLQoEcG9zdBgEIAEoCzIdLnppdGFkZWwuc2FtbC52Mi5Qb3N0UmVzcG9uc2VIAEIJCgdiaW5kaW5nIhIKEFJlZGlyZWN0UmVzcG9uc2UiOgoMUG9zdFJlc3BvbnNlEhMKC3JlbGF5X3N0YXRlGAEgASgJEhUKDXNhbWxfcmVzcG9uc2UYAiABKAky2wEKC1NBTUxTZXJ2aWNlEmUKDkdldFNBTUxSZXF1ZXN0EiYueml0YWRlbC5zYW1sLnYyLkdldFNBTUxSZXF1ZXN0UmVxdWVzdBonLnppdGFkZWwuc2FtbC52Mi5HZXRTQU1MUmVxdWVzdFJlc3BvbnNlKAAwABJlCg5DcmVhdGVSZXNwb25zZRImLnppdGFkZWwuc2FtbC52Mi5DcmVhdGVSZXNwb25zZVJlcXVlc3QaJy56aXRhZGVsLnNhbWwudjIuQ3JlYXRlUmVzcG9uc2VSZXNwb25zZSgAMABiBnByb3RvMw", [file_zitadel_object_v2_object, file_zitadel_saml_v2_authorization]);

/**
 * @generated from message zitadel.saml.v2.GetSAMLRequestRequest
 */
export type GetSAMLRequestRequest = Message<"zitadel.saml.v2.GetSAMLRequestRequest"> & {
  /**
   * @generated from field: string saml_request_id = 1;
   */
  samlRequestId: string;
};

/**
 * Describes the message zitadel.saml.v2.GetSAMLRequestRequest.
 * Use `create(GetSAMLRequestRequestSchema)` to create a new message.
 */
export const GetSAMLRequestRequestSchema: GenMessage<GetSAMLRequestRequest> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 0);

/**
 * @generated from message zitadel.saml.v2.GetSAMLRequestResponse
 */
export type GetSAMLRequestResponse = Message<"zitadel.saml.v2.GetSAMLRequestResponse"> & {
  /**
   * @generated from field: zitadel.saml.v2.SAMLRequest saml_request = 1;
   */
  samlRequest?: SAMLRequest | undefined;
};

/**
 * Describes the message zitadel.saml.v2.GetSAMLRequestResponse.
 * Use `create(GetSAMLRequestResponseSchema)` to create a new message.
 */
export const GetSAMLRequestResponseSchema: GenMessage<GetSAMLRequestResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 1);

/**
 * @generated from message zitadel.saml.v2.CreateResponseRequest
 */
export type CreateResponseRequest = Message<"zitadel.saml.v2.CreateResponseRequest"> & {
  /**
   * @generated from field: string saml_request_id = 1;
   */
  samlRequestId: string;

  /**
   * @generated from oneof zitadel.saml.v2.CreateResponseRequest.response_kind
   */
  responseKind: {
    /**
     * @generated from field: zitadel.saml.v2.Session session = 2;
     */
    value: Session;
    case: "session";
  } | {
    /**
     * @generated from field: zitadel.saml.v2.AuthorizationError error = 3;
     */
    value: AuthorizationError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.saml.v2.CreateResponseRequest.
 * Use `create(CreateResponseRequestSchema)` to create a new message.
 */
export const CreateResponseRequestSchema: GenMessage<CreateResponseRequest> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 2);

/**
 * @generated from message zitadel.saml.v2.Session
 */
export type Session = Message<"zitadel.saml.v2.Session"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string session_token = 2;
   */
  sessionToken: string;
};

/**
 * Describes the message zitadel.saml.v2.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema: GenMessage<Session> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 3);

/**
 * @generated from message zitadel.saml.v2.CreateResponseResponse
 */
export type CreateResponseResponse = Message<"zitadel.saml.v2.CreateResponseResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details | undefined;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from oneof zitadel.saml.v2.CreateResponseResponse.binding
   */
  binding: {
    /**
     * @generated from field: zitadel.saml.v2.RedirectResponse redirect = 3;
     */
    value: RedirectResponse;
    case: "redirect";
  } | {
    /**
     * @generated from field: zitadel.saml.v2.PostResponse post = 4;
     */
    value: PostResponse;
    case: "post";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.saml.v2.CreateResponseResponse.
 * Use `create(CreateResponseResponseSchema)` to create a new message.
 */
export const CreateResponseResponseSchema: GenMessage<CreateResponseResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 4);

/**
 * @generated from message zitadel.saml.v2.RedirectResponse
 */
export type RedirectResponse = Message<"zitadel.saml.v2.RedirectResponse"> & {
};

/**
 * Describes the message zitadel.saml.v2.RedirectResponse.
 * Use `create(RedirectResponseSchema)` to create a new message.
 */
export const RedirectResponseSchema: GenMessage<RedirectResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 5);

/**
 * @generated from message zitadel.saml.v2.PostResponse
 */
export type PostResponse = Message<"zitadel.saml.v2.PostResponse"> & {
  /**
   * @generated from field: string relay_state = 1;
   */
  relayState: string;

  /**
   * @generated from field: string saml_response = 2;
   */
  samlResponse: string;
};

/**
 * Describes the message zitadel.saml.v2.PostResponse.
 * Use `create(PostResponseSchema)` to create a new message.
 */
export const PostResponseSchema: GenMessage<PostResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_saml_service, 6);

/**
 * @generated from service zitadel.saml.v2.SAMLService
 */
export const SAMLService: GenService<{
  /**
   * @generated from rpc zitadel.saml.v2.SAMLService.GetSAMLRequest
   */
  getSAMLRequest: {
    methodKind: "unary";
    input: typeof GetSAMLRequestRequestSchema;
    output: typeof GetSAMLRequestResponseSchema;
  },
  /**
   * @generated from rpc zitadel.saml.v2.SAMLService.CreateResponse
   */
  createResponse: {
    methodKind: "unary";
    input: typeof CreateResponseRequestSchema;
    output: typeof CreateResponseResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_zitadel_saml_v2_saml_service, 0);

