// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/object/v2/object.proto (package zitadel.object.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/object/v2/object.proto.
 */
export const file_zitadel_object_v2_object: GenFile = /*@__PURE__*/
  fileDesc("Ch56aXRhZGVsL29iamVjdC92Mi9vYmplY3QucHJvdG8SEXppdGFkZWwub2JqZWN0LnYyIj0KDE9yZ2FuaXNhdGlvbhIQCgZvcmdfaWQYASABKAlIABIUCgpvcmdfZG9tYWluGAIgASgJSABCBQoDb3JnIj0KDE9yZ2FuaXphdGlvbhIQCgZvcmdfaWQYASABKAlIABIUCgpvcmdfZG9tYWluGAIgASgJSABCBQoDb3JnIkgKDlJlcXVlc3RDb250ZXh0EhAKBm9yZ19pZBgBIAEoCUgAEhIKCGluc3RhbmNlGAIgASgISABCEAoOcmVzb3VyY2Vfb3duZXIiNwoJTGlzdFF1ZXJ5Eg4KBm9mZnNldBgBIAEoBBINCgVsaW1pdBgCIAEoDRILCgNhc2MYAyABKAgilwEKB0RldGFpbHMSEAoIc2VxdWVuY2UYASABKAQSLwoLY2hhbmdlX2RhdGUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhYKDnJlc291cmNlX293bmVyGAMgASgJEjEKDWNyZWF0aW9uX2RhdGUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIm4KC0xpc3REZXRhaWxzEhQKDHRvdGFsX3Jlc3VsdBgBIAEoBBIaChJwcm9jZXNzZWRfc2VxdWVuY2UYAiABKAQSLQoJdGltZXN0YW1wGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCrFAgoPVGV4dFF1ZXJ5TWV0aG9kEhwKGFRFWFRfUVVFUllfTUVUSE9EX0VRVUFMUxAAEigKJFRFWFRfUVVFUllfTUVUSE9EX0VRVUFMU19JR05PUkVfQ0FTRRABEiEKHVRFWFRfUVVFUllfTUVUSE9EX1NUQVJUU19XSVRIEAISLQopVEVYVF9RVUVSWV9NRVRIT0RfU1RBUlRTX1dJVEhfSUdOT1JFX0NBU0UQAxIeChpURVhUX1FVRVJZX01FVEhPRF9DT05UQUlOUxAEEioKJlRFWFRfUVVFUllfTUVUSE9EX0NPTlRBSU5TX0lHTk9SRV9DQVNFEAUSHwobVEVYVF9RVUVSWV9NRVRIT0RfRU5EU19XSVRIEAYSKwonVEVYVF9RVUVSWV9NRVRIT0RfRU5EU19XSVRIX0lHTk9SRV9DQVNFEAcqKwoPTGlzdFF1ZXJ5TWV0aG9kEhgKFExJU1RfUVVFUllfTUVUSE9EX0lOEAAq1wEKFFRpbWVzdGFtcFF1ZXJ5TWV0aG9kEiEKHVRJTUVTVEFNUF9RVUVSWV9NRVRIT0RfRVFVQUxTEAASIgoeVElNRVNUQU1QX1FVRVJZX01FVEhPRF9HUkVBVEVSEAESLAooVElNRVNUQU1QX1FVRVJZX01FVEhPRF9HUkVBVEVSX09SX0VRVUFMUxACEh8KG1RJTUVTVEFNUF9RVUVSWV9NRVRIT0RfTEVTUxADEikKJVRJTUVTVEFNUF9RVUVSWV9NRVRIT0RfTEVTU19PUl9FUVVBTFMQBGIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message zitadel.object.v2.Organisation
 */
export type Organisation = Message<"zitadel.object.v2.Organisation"> & {
  /**
   * @generated from oneof zitadel.object.v2.Organisation.org
   */
  org: {
    /**
     * @generated from field: string org_id = 1;
     */
    value: string;
    case: "orgId";
  } | {
    /**
     * @generated from field: string org_domain = 2;
     */
    value: string;
    case: "orgDomain";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.object.v2.Organisation.
 * Use `create(OrganisationSchema)` to create a new message.
 */
export const OrganisationSchema: GenMessage<Organisation> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 0);

/**
 * @generated from message zitadel.object.v2.Organization
 */
export type Organization = Message<"zitadel.object.v2.Organization"> & {
  /**
   * @generated from oneof zitadel.object.v2.Organization.org
   */
  org: {
    /**
     * @generated from field: string org_id = 1;
     */
    value: string;
    case: "orgId";
  } | {
    /**
     * @generated from field: string org_domain = 2;
     */
    value: string;
    case: "orgDomain";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.object.v2.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export const OrganizationSchema: GenMessage<Organization> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 1);

/**
 * @generated from message zitadel.object.v2.RequestContext
 */
export type RequestContext = Message<"zitadel.object.v2.RequestContext"> & {
  /**
   * @generated from oneof zitadel.object.v2.RequestContext.resource_owner
   */
  resourceOwner: {
    /**
     * @generated from field: string org_id = 1;
     */
    value: string;
    case: "orgId";
  } | {
    /**
     * @generated from field: bool instance = 2;
     */
    value: boolean;
    case: "instance";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.object.v2.RequestContext.
 * Use `create(RequestContextSchema)` to create a new message.
 */
export const RequestContextSchema: GenMessage<RequestContext> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 2);

/**
 * @generated from message zitadel.object.v2.ListQuery
 */
export type ListQuery = Message<"zitadel.object.v2.ListQuery"> & {
  /**
   * @generated from field: uint64 offset = 1;
   */
  offset: bigint;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: bool asc = 3;
   */
  asc: boolean;
};

/**
 * Describes the message zitadel.object.v2.ListQuery.
 * Use `create(ListQuerySchema)` to create a new message.
 */
export const ListQuerySchema: GenMessage<ListQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 3);

/**
 * @generated from message zitadel.object.v2.Details
 */
export type Details = Message<"zitadel.object.v2.Details"> & {
  /**
   * @generated from field: uint64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: Timestamp | undefined;

  /**
   * @generated from field: string resource_owner = 3;
   */
  resourceOwner: string;

  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 4;
   */
  creationDate?: Timestamp | undefined;
};

/**
 * Describes the message zitadel.object.v2.Details.
 * Use `create(DetailsSchema)` to create a new message.
 */
export const DetailsSchema: GenMessage<Details> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 4);

/**
 * @generated from message zitadel.object.v2.ListDetails
 */
export type ListDetails = Message<"zitadel.object.v2.ListDetails"> & {
  /**
   * @generated from field: uint64 total_result = 1;
   */
  totalResult: bigint;

  /**
   * @generated from field: uint64 processed_sequence = 2;
   */
  processedSequence: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp | undefined;
};

/**
 * Describes the message zitadel.object.v2.ListDetails.
 * Use `create(ListDetailsSchema)` to create a new message.
 */
export const ListDetailsSchema: GenMessage<ListDetails> = /*@__PURE__*/
  messageDesc(file_zitadel_object_v2_object, 5);

/**
 * @generated from enum zitadel.object.v2.TextQueryMethod
 */
export enum TextQueryMethod {
  /**
   * @generated from enum value: TEXT_QUERY_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE = 1;
   */
  EQUALS_IGNORE_CASE = 1,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_STARTS_WITH = 2;
   */
  STARTS_WITH = 2,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE = 3;
   */
  STARTS_WITH_IGNORE_CASE = 3,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_CONTAINS = 4;
   */
  CONTAINS = 4,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE = 5;
   */
  CONTAINS_IGNORE_CASE = 5,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_ENDS_WITH = 6;
   */
  ENDS_WITH = 6,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE = 7;
   */
  ENDS_WITH_IGNORE_CASE = 7,
}

/**
 * Describes the enum zitadel.object.v2.TextQueryMethod.
 */
export const TextQueryMethodSchema: GenEnum<TextQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object_v2_object, 0);

/**
 * @generated from enum zitadel.object.v2.ListQueryMethod
 */
export enum ListQueryMethod {
  /**
   * @generated from enum value: LIST_QUERY_METHOD_IN = 0;
   */
  IN = 0,
}

/**
 * Describes the enum zitadel.object.v2.ListQueryMethod.
 */
export const ListQueryMethodSchema: GenEnum<ListQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object_v2_object, 1);

/**
 * @generated from enum zitadel.object.v2.TimestampQueryMethod
 */
export enum TimestampQueryMethod {
  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_GREATER = 1;
   */
  GREATER = 1,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_GREATER_OR_EQUALS = 2;
   */
  GREATER_OR_EQUALS = 2,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_LESS = 3;
   */
  LESS = 3,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_LESS_OR_EQUALS = 4;
   */
  LESS_OR_EQUALS = 4,
}

/**
 * Describes the enum zitadel.object.v2.TimestampQueryMethod.
 */
export const TimestampQueryMethodSchema: GenEnum<TimestampQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object_v2_object, 2);

