// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/message.proto (package zitadel.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/message.proto.
 */
export const file_zitadel_message: GenFile = /*@__PURE__*/
  fileDesc("ChV6aXRhZGVsL21lc3NhZ2UucHJvdG8SCnppdGFkZWwudjEiKgoLRXJyb3JEZXRhaWwSCgoCaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCSJNChVDcmVkZW50aWFsc0NoZWNrRXJyb3ISCgoCaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIXCg9mYWlsZWRfYXR0ZW1wdHMYAyABKAUiOgoQTG9jYWxpemVkTWVzc2FnZRILCgNrZXkYASABKAkSGQoRbG9jYWxpemVkX21lc3NhZ2UYAiABKAliBnByb3RvMw");

/**
 * @generated from message zitadel.v1.ErrorDetail
 */
export type ErrorDetail = Message<"zitadel.v1.ErrorDetail"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message zitadel.v1.ErrorDetail.
 * Use `create(ErrorDetailSchema)` to create a new message.
 */
export const ErrorDetailSchema: GenMessage<ErrorDetail> = /*@__PURE__*/
  messageDesc(file_zitadel_message, 0);

/**
 * @generated from message zitadel.v1.CredentialsCheckError
 */
export type CredentialsCheckError = Message<"zitadel.v1.CredentialsCheckError"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: int32 failed_attempts = 3;
   */
  failedAttempts: number;
};

/**
 * Describes the message zitadel.v1.CredentialsCheckError.
 * Use `create(CredentialsCheckErrorSchema)` to create a new message.
 */
export const CredentialsCheckErrorSchema: GenMessage<CredentialsCheckError> = /*@__PURE__*/
  messageDesc(file_zitadel_message, 1);

/**
 * @generated from message zitadel.v1.LocalizedMessage
 */
export type LocalizedMessage = Message<"zitadel.v1.LocalizedMessage"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string localized_message = 2;
   */
  localizedMessage: string;
};

/**
 * Describes the message zitadel.v1.LocalizedMessage.
 * Use `create(LocalizedMessageSchema)` to create a new message.
 */
export const LocalizedMessageSchema: GenMessage<LocalizedMessage> = /*@__PURE__*/
  messageDesc(file_zitadel_message, 2);

