// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/object.proto (package zitadel.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/object.proto.
 */
export const file_zitadel_object: GenFile = /*@__PURE__*/
  fileDesc("ChR6aXRhZGVsL29iamVjdC5wcm90bxIKeml0YWRlbC52MSKdAQoNT2JqZWN0RGV0YWlscxIQCghzZXF1ZW5jZRgBIAEoBBIxCg1jcmVhdGlvbl9kYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgtjaGFuZ2VfZGF0ZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFgoOcmVzb3VyY2Vfb3duZXIYBCABKAkiNwoJTGlzdFF1ZXJ5Eg4KBm9mZnNldBgBIAEoBBINCgVsaW1pdBgCIAEoDRILCgNhc2MYAyABKAgicwoLTGlzdERldGFpbHMSFAoMdG90YWxfcmVzdWx0GAEgASgEEhoKEnByb2Nlc3NlZF9zZXF1ZW5jZRgCIAEoBBIyCg52aWV3X3RpbWVzdGFtcBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqxQIKD1RleHRRdWVyeU1ldGhvZBIcChhURVhUX1FVRVJZX01FVEhPRF9FUVVBTFMQABIoCiRURVhUX1FVRVJZX01FVEhPRF9FUVVBTFNfSUdOT1JFX0NBU0UQARIhCh1URVhUX1FVRVJZX01FVEhPRF9TVEFSVFNfV0lUSBACEi0KKVRFWFRfUVVFUllfTUVUSE9EX1NUQVJUU19XSVRIX0lHTk9SRV9DQVNFEAMSHgoaVEVYVF9RVUVSWV9NRVRIT0RfQ09OVEFJTlMQBBIqCiZURVhUX1FVRVJZX01FVEhPRF9DT05UQUlOU19JR05PUkVfQ0FTRRAFEh8KG1RFWFRfUVVFUllfTUVUSE9EX0VORFNfV0lUSBAGEisKJ1RFWFRfUVVFUllfTUVUSE9EX0VORFNfV0lUSF9JR05PUkVfQ0FTRRAHKisKD0xpc3RRdWVyeU1ldGhvZBIYChRMSVNUX1FVRVJZX01FVEhPRF9JThAAKtcBChRUaW1lc3RhbXBRdWVyeU1ldGhvZBIhCh1USU1FU1RBTVBfUVVFUllfTUVUSE9EX0VRVUFMUxAAEiIKHlRJTUVTVEFNUF9RVUVSWV9NRVRIT0RfR1JFQVRFUhABEiwKKFRJTUVTVEFNUF9RVUVSWV9NRVRIT0RfR1JFQVRFUl9PUl9FUVVBTFMQAhIfChtUSU1FU1RBTVBfUVVFUllfTUVUSE9EX0xFU1MQAxIpCiVUSU1FU1RBTVBfUVVFUllfTUVUSE9EX0xFU1NfT1JfRVFVQUxTEARiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message zitadel.v1.ObjectDetails
 */
export type ObjectDetails = Message<"zitadel.v1.ObjectDetails"> & {
  /**
   * @generated from field: uint64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp change_date = 3;
   */
  changeDate?: Timestamp | undefined;

  /**
   * @generated from field: string resource_owner = 4;
   */
  resourceOwner: string;
};

/**
 * Describes the message zitadel.v1.ObjectDetails.
 * Use `create(ObjectDetailsSchema)` to create a new message.
 */
export const ObjectDetailsSchema: GenMessage<ObjectDetails> = /*@__PURE__*/
  messageDesc(file_zitadel_object, 0);

/**
 * @generated from message zitadel.v1.ListQuery
 */
export type ListQuery = Message<"zitadel.v1.ListQuery"> & {
  /**
   * @generated from field: uint64 offset = 1;
   */
  offset: bigint;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: bool asc = 3;
   */
  asc: boolean;
};

/**
 * Describes the message zitadel.v1.ListQuery.
 * Use `create(ListQuerySchema)` to create a new message.
 */
export const ListQuerySchema: GenMessage<ListQuery> = /*@__PURE__*/
  messageDesc(file_zitadel_object, 1);

/**
 * @generated from message zitadel.v1.ListDetails
 */
export type ListDetails = Message<"zitadel.v1.ListDetails"> & {
  /**
   * @generated from field: uint64 total_result = 1;
   */
  totalResult: bigint;

  /**
   * @generated from field: uint64 processed_sequence = 2;
   */
  processedSequence: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp view_timestamp = 3;
   */
  viewTimestamp?: Timestamp | undefined;
};

/**
 * Describes the message zitadel.v1.ListDetails.
 * Use `create(ListDetailsSchema)` to create a new message.
 */
export const ListDetailsSchema: GenMessage<ListDetails> = /*@__PURE__*/
  messageDesc(file_zitadel_object, 2);

/**
 * @generated from enum zitadel.v1.TextQueryMethod
 */
export enum TextQueryMethod {
  /**
   * @generated from enum value: TEXT_QUERY_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE = 1;
   */
  EQUALS_IGNORE_CASE = 1,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_STARTS_WITH = 2;
   */
  STARTS_WITH = 2,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE = 3;
   */
  STARTS_WITH_IGNORE_CASE = 3,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_CONTAINS = 4;
   */
  CONTAINS = 4,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE = 5;
   */
  CONTAINS_IGNORE_CASE = 5,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_ENDS_WITH = 6;
   */
  ENDS_WITH = 6,

  /**
   * @generated from enum value: TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE = 7;
   */
  ENDS_WITH_IGNORE_CASE = 7,
}

/**
 * Describes the enum zitadel.v1.TextQueryMethod.
 */
export const TextQueryMethodSchema: GenEnum<TextQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object, 0);

/**
 * @generated from enum zitadel.v1.ListQueryMethod
 */
export enum ListQueryMethod {
  /**
   * @generated from enum value: LIST_QUERY_METHOD_IN = 0;
   */
  IN = 0,
}

/**
 * Describes the enum zitadel.v1.ListQueryMethod.
 */
export const ListQueryMethodSchema: GenEnum<ListQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object, 1);

/**
 * @generated from enum zitadel.v1.TimestampQueryMethod
 */
export enum TimestampQueryMethod {
  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_GREATER = 1;
   */
  GREATER = 1,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_GREATER_OR_EQUALS = 2;
   */
  GREATER_OR_EQUALS = 2,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_LESS = 3;
   */
  LESS = 3,

  /**
   * @generated from enum value: TIMESTAMP_QUERY_METHOD_LESS_OR_EQUALS = 4;
   */
  LESS_OR_EQUALS = 4,
}

/**
 * Describes the enum zitadel.v1.TimestampQueryMethod.
 */
export const TimestampQueryMethodSchema: GenEnum<TimestampQueryMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_object, 2);

