// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/auth.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/auth.proto.
 */
export const file_zitadel_user_v2_auth: GenFile = /*@__PURE__*/
  fileDesc("Chp6aXRhZGVsL3VzZXIvdjIvYXV0aC5wcm90bxIPeml0YWRlbC51c2VyLnYyIkkKG1NlbmRQYXNza2V5UmVnaXN0cmF0aW9uTGluaxIZCgx1cmxfdGVtcGxhdGUYASABKAlIAIgBAUIPCg1fdXJsX3RlbXBsYXRlIh8KHVJldHVyblBhc3NrZXlSZWdpc3RyYXRpb25Db2RlIjMKF1Bhc3NrZXlSZWdpc3RyYXRpb25Db2RlEgoKAmlkGAEgASgJEgwKBGNvZGUYAiABKAkqiwEKFFBhc3NrZXlBdXRoZW50aWNhdG9yEiUKIVBBU1NLRVlfQVVUSEVOVElDQVRPUl9VTlNQRUNJRklFRBAAEiIKHlBBU1NLRVlfQVVUSEVOVElDQVRPUl9QTEFURk9STRABEigKJFBBU1NLRVlfQVVUSEVOVElDQVRPUl9DUk9TU19QTEFURk9STRACYgZwcm90bzM");

/**
 * @generated from message zitadel.user.v2.SendPasskeyRegistrationLink
 */
export type SendPasskeyRegistrationLink = Message<"zitadel.user.v2.SendPasskeyRegistrationLink"> & {
  /**
   * @generated from field: optional string url_template = 1;
   */
  urlTemplate?: string | undefined;
};

/**
 * Describes the message zitadel.user.v2.SendPasskeyRegistrationLink.
 * Use `create(SendPasskeyRegistrationLinkSchema)` to create a new message.
 */
export const SendPasskeyRegistrationLinkSchema: GenMessage<SendPasskeyRegistrationLink> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_auth, 0);

/**
 * @generated from message zitadel.user.v2.ReturnPasskeyRegistrationCode
 */
export type ReturnPasskeyRegistrationCode = Message<"zitadel.user.v2.ReturnPasskeyRegistrationCode"> & {
};

/**
 * Describes the message zitadel.user.v2.ReturnPasskeyRegistrationCode.
 * Use `create(ReturnPasskeyRegistrationCodeSchema)` to create a new message.
 */
export const ReturnPasskeyRegistrationCodeSchema: GenMessage<ReturnPasskeyRegistrationCode> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_auth, 1);

/**
 * @generated from message zitadel.user.v2.PasskeyRegistrationCode
 */
export type PasskeyRegistrationCode = Message<"zitadel.user.v2.PasskeyRegistrationCode"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message zitadel.user.v2.PasskeyRegistrationCode.
 * Use `create(PasskeyRegistrationCodeSchema)` to create a new message.
 */
export const PasskeyRegistrationCodeSchema: GenMessage<PasskeyRegistrationCode> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_auth, 2);

/**
 * @generated from enum zitadel.user.v2.PasskeyAuthenticator
 */
export enum PasskeyAuthenticator {
  /**
   * @generated from enum value: PASSKEY_AUTHENTICATOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PASSKEY_AUTHENTICATOR_PLATFORM = 1;
   */
  PLATFORM = 1,

  /**
   * @generated from enum value: PASSKEY_AUTHENTICATOR_CROSS_PLATFORM = 2;
   */
  CROSS_PLATFORM = 2,
}

/**
 * Describes the enum zitadel.user.v2.PasskeyAuthenticator.
 */
export const PasskeyAuthenticatorSchema: GenEnum<PasskeyAuthenticator> = /*@__PURE__*/
  enumDesc(file_zitadel_user_v2_auth, 0);

