// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/idp.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/idp.proto.
 */
export const file_zitadel_user_v2_idp: GenFile = /*@__PURE__*/
  fileDesc("Chl6aXRhZGVsL3VzZXIvdjIvaWRwLnByb3RvEg96aXRhZGVsLnVzZXIudjIiNQoPTERBUENyZWRlbnRpYWxzEhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIkwKDFJlZGlyZWN0VVJMcxITCgtzdWNjZXNzX3VybBgBIAEoCRITCgtmYWlsdXJlX3VybBgCIAEoCRISCgpsb2dpbl9oaW50GAMgASgJIk0KCUlEUEludGVudBIVCg1pZHBfaW50ZW50X2lkGAEgASgJEhgKEGlkcF9pbnRlbnRfdG9rZW4YAiABKAkSDwoHdXNlcl9pZBgDIAEoCSKzAgoOSURQSW5mb3JtYXRpb24SOwoFb2F1dGgYASABKAsyKi56aXRhZGVsLnVzZXIudjIuSURQT0F1dGhBY2Nlc3NJbmZvcm1hdGlvbkgAEjkKBGxkYXAYBiABKAsyKS56aXRhZGVsLnVzZXIudjIuSURQTERBUEFjY2Vzc0luZm9ybWF0aW9uSAASOQoEc2FtbBgHIAEoCzIpLnppdGFkZWwudXNlci52Mi5JRFBTQU1MQWNjZXNzSW5mb3JtYXRpb25IABIOCgZpZHBfaWQYAiABKAkSDwoHdXNlcl9pZBgDIAEoCRIRCgl1c2VyX25hbWUYBCABKAkSMAoPcmF3X2luZm9ybWF0aW9uGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEIICgZhY2Nlc3MigwEKGUlEUE9BdXRoQWNjZXNzSW5mb3JtYXRpb24SFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKCGlkX3Rva2VuGAIgASgJSACIAQESGgoNcmVmcmVzaF90b2tlbhgDIAEoCUgBiAEBQgsKCV9pZF90b2tlbkIQCg5fcmVmcmVzaF90b2tlbiJHChhJRFBMREFQQWNjZXNzSW5mb3JtYXRpb24SKwoKYXR0cmlidXRlcxgBIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QiLQoYSURQU0FNTEFjY2Vzc0luZm9ybWF0aW9uEhEKCWFzc2VydGlvbhgBIAEoDCI9CgdJRFBMaW5rEg4KBmlkcF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhEKCXVzZXJfbmFtZRgDIAEoCSJ9CghGb3JtRGF0YRILCgN1cmwYASABKAkSNQoGZmllbGRzGAIgAygLMiUueml0YWRlbC51c2VyLnYyLkZvcm1EYXRhLkZpZWxkc0VudHJ5Gi0KC0ZpZWxkc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFiBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * @generated from message zitadel.user.v2.LDAPCredentials
 */
export type LDAPCredentials = Message<"zitadel.user.v2.LDAPCredentials"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message zitadel.user.v2.LDAPCredentials.
 * Use `create(LDAPCredentialsSchema)` to create a new message.
 */
export const LDAPCredentialsSchema: GenMessage<LDAPCredentials> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 0);

/**
 * @generated from message zitadel.user.v2.RedirectURLs
 */
export type RedirectURLs = Message<"zitadel.user.v2.RedirectURLs"> & {
  /**
   * @generated from field: string success_url = 1;
   */
  successUrl: string;

  /**
   * @generated from field: string failure_url = 2;
   */
  failureUrl: string;

  /**
   * @generated from field: string login_hint = 3;
   */
  loginHint: string;
};

/**
 * Describes the message zitadel.user.v2.RedirectURLs.
 * Use `create(RedirectURLsSchema)` to create a new message.
 */
export const RedirectURLsSchema: GenMessage<RedirectURLs> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 1);

/**
 * @generated from message zitadel.user.v2.IDPIntent
 */
export type IDPIntent = Message<"zitadel.user.v2.IDPIntent"> & {
  /**
   * @generated from field: string idp_intent_id = 1;
   */
  idpIntentId: string;

  /**
   * @generated from field: string idp_intent_token = 2;
   */
  idpIntentToken: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;
};

/**
 * Describes the message zitadel.user.v2.IDPIntent.
 * Use `create(IDPIntentSchema)` to create a new message.
 */
export const IDPIntentSchema: GenMessage<IDPIntent> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 2);

/**
 * @generated from message zitadel.user.v2.IDPInformation
 */
export type IDPInformation = Message<"zitadel.user.v2.IDPInformation"> & {
  /**
   * @generated from oneof zitadel.user.v2.IDPInformation.access
   */
  access: {
    /**
     * @generated from field: zitadel.user.v2.IDPOAuthAccessInformation oauth = 1;
     */
    value: IDPOAuthAccessInformation;
    case: "oauth";
  } | {
    /**
     * @generated from field: zitadel.user.v2.IDPLDAPAccessInformation ldap = 6;
     */
    value: IDPLDAPAccessInformation;
    case: "ldap";
  } | {
    /**
     * @generated from field: zitadel.user.v2.IDPSAMLAccessInformation saml = 7;
     */
    value: IDPSAMLAccessInformation;
    case: "saml";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string idp_id = 2;
   */
  idpId: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 4;
   */
  userName: string;

  /**
   * @generated from field: google.protobuf.Struct raw_information = 5;
   */
  rawInformation?: JsonObject | undefined;
};

/**
 * Describes the message zitadel.user.v2.IDPInformation.
 * Use `create(IDPInformationSchema)` to create a new message.
 */
export const IDPInformationSchema: GenMessage<IDPInformation> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 3);

/**
 * @generated from message zitadel.user.v2.IDPOAuthAccessInformation
 */
export type IDPOAuthAccessInformation = Message<"zitadel.user.v2.IDPOAuthAccessInformation"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: optional string id_token = 2;
   */
  idToken?: string | undefined;

  /**
   * @generated from field: optional string refresh_token = 3;
   */
  refreshToken?: string | undefined;
};

/**
 * Describes the message zitadel.user.v2.IDPOAuthAccessInformation.
 * Use `create(IDPOAuthAccessInformationSchema)` to create a new message.
 */
export const IDPOAuthAccessInformationSchema: GenMessage<IDPOAuthAccessInformation> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 4);

/**
 * @generated from message zitadel.user.v2.IDPLDAPAccessInformation
 */
export type IDPLDAPAccessInformation = Message<"zitadel.user.v2.IDPLDAPAccessInformation"> & {
  /**
   * @generated from field: google.protobuf.Struct attributes = 1;
   */
  attributes?: JsonObject | undefined;
};

/**
 * Describes the message zitadel.user.v2.IDPLDAPAccessInformation.
 * Use `create(IDPLDAPAccessInformationSchema)` to create a new message.
 */
export const IDPLDAPAccessInformationSchema: GenMessage<IDPLDAPAccessInformation> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 5);

/**
 * @generated from message zitadel.user.v2.IDPSAMLAccessInformation
 */
export type IDPSAMLAccessInformation = Message<"zitadel.user.v2.IDPSAMLAccessInformation"> & {
  /**
   * @generated from field: bytes assertion = 1;
   */
  assertion: Uint8Array;
};

/**
 * Describes the message zitadel.user.v2.IDPSAMLAccessInformation.
 * Use `create(IDPSAMLAccessInformationSchema)` to create a new message.
 */
export const IDPSAMLAccessInformationSchema: GenMessage<IDPSAMLAccessInformation> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 6);

/**
 * @generated from message zitadel.user.v2.IDPLink
 */
export type IDPLink = Message<"zitadel.user.v2.IDPLink"> & {
  /**
   * @generated from field: string idp_id = 1;
   */
  idpId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 3;
   */
  userName: string;
};

/**
 * Describes the message zitadel.user.v2.IDPLink.
 * Use `create(IDPLinkSchema)` to create a new message.
 */
export const IDPLinkSchema: GenMessage<IDPLink> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 7);

/**
 * @generated from message zitadel.user.v2.FormData
 */
export type FormData = Message<"zitadel.user.v2.FormData"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: map<string, string> fields = 2;
   */
  fields: { [key: string]: string };
};

/**
 * Describes the message zitadel.user.v2.FormData.
 * Use `create(FormDataSchema)` to create a new message.
 */
export const FormDataSchema: GenMessage<FormData> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_idp, 8);

