// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/key.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { IDFilter, TimestampFilter } from "../../filter/v2/filter_pb";
import { file_zitadel_filter_v2_filter } from "../../filter/v2/filter_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/key.proto.
 */
export const file_zitadel_user_v2_key: GenFile = /*@__PURE__*/
  fileDesc("Chl6aXRhZGVsL3VzZXIvdjIva2V5LnByb3RvEg96aXRhZGVsLnVzZXIudjIi1AEKA0tleRIxCg1jcmVhdGlvbl9kYXRlGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgtjaGFuZ2VfZGF0ZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASCgoCaWQYAyABKAkSDwoHdXNlcl9pZBgEIAEoCRIXCg9vcmdhbml6YXRpb25faWQYBSABKAkSMwoPZXhwaXJhdGlvbl9kYXRlGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCLRAgoQS2V5c1NlYXJjaEZpbHRlchI0Cg1rZXlfaWRfZmlsdGVyGAEgASgLMhsueml0YWRlbC5maWx0ZXIudjIuSURGaWx0ZXJIABI1Cg51c2VyX2lkX2ZpbHRlchgCIAEoCzIbLnppdGFkZWwuZmlsdGVyLnYyLklERmlsdGVySAASPQoWb3JnYW5pemF0aW9uX2lkX2ZpbHRlchgDIAEoCzIbLnppdGFkZWwuZmlsdGVyLnYyLklERmlsdGVySAASQQoTY3JlYXRlZF9kYXRlX2ZpbHRlchgEIAEoCzIiLnppdGFkZWwuZmlsdGVyLnYyLlRpbWVzdGFtcEZpbHRlckgAEkQKFmV4cGlyYXRpb25fZGF0ZV9maWx0ZXIYBSABKAsyIi56aXRhZGVsLmZpbHRlci52Mi5UaW1lc3RhbXBGaWx0ZXJIAEIICgZmaWx0ZXIqzgEKDEtleUZpZWxkTmFtZRIeChpLRVlfRklFTERfTkFNRV9VTlNQRUNJRklFRBAAEh8KG0tFWV9GSUVMRF9OQU1FX0NSRUFURURfREFURRABEhUKEUtFWV9GSUVMRF9OQU1FX0lEEAISGgoWS0VZX0ZJRUxEX05BTUVfVVNFUl9JRBADEiIKHktFWV9GSUVMRF9OQU1FX09SR0FOSVpBVElPTl9JRBAEEiYKIktFWV9GSUVMRF9OQU1FX0tFWV9FWFBJUkFUSU9OX0RBVEUQBWIGcHJvdG8z", [file_google_protobuf_timestamp, file_zitadel_filter_v2_filter]);

/**
 * @generated from message zitadel.user.v2.Key
 */
export type Key = Message<"zitadel.user.v2.Key"> & {
  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 1;
   */
  creationDate?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: Timestamp | undefined;

  /**
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;

  /**
   * @generated from field: string organization_id = 5;
   */
  organizationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp expiration_date = 6;
   */
  expirationDate?: Timestamp | undefined;
};

/**
 * Describes the message zitadel.user.v2.Key.
 * Use `create(KeySchema)` to create a new message.
 */
export const KeySchema: GenMessage<Key> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_key, 0);

/**
 * @generated from message zitadel.user.v2.KeysSearchFilter
 */
export type KeysSearchFilter = Message<"zitadel.user.v2.KeysSearchFilter"> & {
  /**
   * @generated from oneof zitadel.user.v2.KeysSearchFilter.filter
   */
  filter: {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter key_id_filter = 1;
     */
    value: IDFilter;
    case: "keyIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter user_id_filter = 2;
     */
    value: IDFilter;
    case: "userIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter organization_id_filter = 3;
     */
    value: IDFilter;
    case: "organizationIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.TimestampFilter created_date_filter = 4;
     */
    value: TimestampFilter;
    case: "createdDateFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.TimestampFilter expiration_date_filter = 5;
     */
    value: TimestampFilter;
    case: "expirationDateFilter";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.user.v2.KeysSearchFilter.
 * Use `create(KeysSearchFilterSchema)` to create a new message.
 */
export const KeysSearchFilterSchema: GenMessage<KeysSearchFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_key, 1);

/**
 * @generated from enum zitadel.user.v2.KeyFieldName
 */
export enum KeyFieldName {
  /**
   * @generated from enum value: KEY_FIELD_NAME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: KEY_FIELD_NAME_CREATED_DATE = 1;
   */
  CREATED_DATE = 1,

  /**
   * @generated from enum value: KEY_FIELD_NAME_ID = 2;
   */
  ID = 2,

  /**
   * @generated from enum value: KEY_FIELD_NAME_USER_ID = 3;
   */
  USER_ID = 3,

  /**
   * @generated from enum value: KEY_FIELD_NAME_ORGANIZATION_ID = 4;
   */
  ORGANIZATION_ID = 4,

  /**
   * @generated from enum value: KEY_FIELD_NAME_KEY_EXPIRATION_DATE = 5;
   */
  KEY_EXPIRATION_DATE = 5,
}

/**
 * Describes the enum zitadel.user.v2.KeyFieldName.
 */
export const KeyFieldNameSchema: GenEnum<KeyFieldName> = /*@__PURE__*/
  enumDesc(file_zitadel_user_v2_key, 0);

