// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/password.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/password.proto.
 */
export const file_zitadel_user_v2_password: GenFile = /*@__PURE__*/
  fileDesc("Ch56aXRhZGVsL3VzZXIvdjIvcGFzc3dvcmQucHJvdG8SD3ppdGFkZWwudXNlci52MiI1CghQYXNzd29yZBIQCghwYXNzd29yZBgBIAEoCRIXCg9jaGFuZ2VfcmVxdWlyZWQYAiABKAgiNwoOSGFzaGVkUGFzc3dvcmQSDAoEaGFzaBgBIAEoCRIXCg9jaGFuZ2VfcmVxdWlyZWQYAiABKAgigQEKFVNlbmRQYXNzd29yZFJlc2V0TGluaxI8ChFub3RpZmljYXRpb25fdHlwZRgBIAEoDjIhLnppdGFkZWwudXNlci52Mi5Ob3RpZmljYXRpb25UeXBlEhkKDHVybF90ZW1wbGF0ZRgCIAEoCUgAiAEBQg8KDV91cmxfdGVtcGxhdGUiGQoXUmV0dXJuUGFzc3dvcmRSZXNldENvZGUi0gEKC1NldFBhc3N3b3JkEi0KCHBhc3N3b3JkGAEgASgLMhkueml0YWRlbC51c2VyLnYyLlBhc3N3b3JkSAASOgoPaGFzaGVkX3Bhc3N3b3JkGAIgASgLMh8ueml0YWRlbC51c2VyLnYyLkhhc2hlZFBhc3N3b3JkSAASGgoQY3VycmVudF9wYXNzd29yZBgDIAEoCUgBEhsKEXZlcmlmaWNhdGlvbl9jb2RlGAQgASgJSAFCDwoNcGFzc3dvcmRfdHlwZUIOCgx2ZXJpZmljYXRpb24qbQoQTm90aWZpY2F0aW9uVHlwZRIhCh1OT1RJRklDQVRJT05fVFlQRV9VbnNwZWNpZmllZBAAEhsKF05PVElGSUNBVElPTl9UWVBFX0VtYWlsEAESGQoVTk9USUZJQ0FUSU9OX1RZUEVfU01TEAJiBnByb3RvMw");

/**
 * @generated from message zitadel.user.v2.Password
 */
export type Password = Message<"zitadel.user.v2.Password"> & {
  /**
   * @generated from field: string password = 1;
   */
  password: string;

  /**
   * @generated from field: bool change_required = 2;
   */
  changeRequired: boolean;
};

/**
 * Describes the message zitadel.user.v2.Password.
 * Use `create(PasswordSchema)` to create a new message.
 */
export const PasswordSchema: GenMessage<Password> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_password, 0);

/**
 * @generated from message zitadel.user.v2.HashedPassword
 */
export type HashedPassword = Message<"zitadel.user.v2.HashedPassword"> & {
  /**
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: bool change_required = 2;
   */
  changeRequired: boolean;
};

/**
 * Describes the message zitadel.user.v2.HashedPassword.
 * Use `create(HashedPasswordSchema)` to create a new message.
 */
export const HashedPasswordSchema: GenMessage<HashedPassword> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_password, 1);

/**
 * @generated from message zitadel.user.v2.SendPasswordResetLink
 */
export type SendPasswordResetLink = Message<"zitadel.user.v2.SendPasswordResetLink"> & {
  /**
   * @generated from field: zitadel.user.v2.NotificationType notification_type = 1;
   */
  notificationType: NotificationType;

  /**
   * @generated from field: optional string url_template = 2;
   */
  urlTemplate?: string | undefined;
};

/**
 * Describes the message zitadel.user.v2.SendPasswordResetLink.
 * Use `create(SendPasswordResetLinkSchema)` to create a new message.
 */
export const SendPasswordResetLinkSchema: GenMessage<SendPasswordResetLink> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_password, 2);

/**
 * @generated from message zitadel.user.v2.ReturnPasswordResetCode
 */
export type ReturnPasswordResetCode = Message<"zitadel.user.v2.ReturnPasswordResetCode"> & {
};

/**
 * Describes the message zitadel.user.v2.ReturnPasswordResetCode.
 * Use `create(ReturnPasswordResetCodeSchema)` to create a new message.
 */
export const ReturnPasswordResetCodeSchema: GenMessage<ReturnPasswordResetCode> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_password, 3);

/**
 * @generated from message zitadel.user.v2.SetPassword
 */
export type SetPassword = Message<"zitadel.user.v2.SetPassword"> & {
  /**
   * @generated from oneof zitadel.user.v2.SetPassword.password_type
   */
  passwordType: {
    /**
     * @generated from field: zitadel.user.v2.Password password = 1;
     */
    value: Password;
    case: "password";
  } | {
    /**
     * @generated from field: zitadel.user.v2.HashedPassword hashed_password = 2;
     */
    value: HashedPassword;
    case: "hashedPassword";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from oneof zitadel.user.v2.SetPassword.verification
   */
  verification: {
    /**
     * @generated from field: string current_password = 3;
     */
    value: string;
    case: "currentPassword";
  } | {
    /**
     * @generated from field: string verification_code = 4;
     */
    value: string;
    case: "verificationCode";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.user.v2.SetPassword.
 * Use `create(SetPasswordSchema)` to create a new message.
 */
export const SetPasswordSchema: GenMessage<SetPassword> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_password, 4);

/**
 * @generated from enum zitadel.user.v2.NotificationType
 */
export enum NotificationType {
  /**
   * @generated from enum value: NOTIFICATION_TYPE_Unspecified = 0;
   */
  Unspecified = 0,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_Email = 1;
   */
  Email = 1,

  /**
   * @generated from enum value: NOTIFICATION_TYPE_SMS = 2;
   */
  SMS = 2,
}

/**
 * Describes the enum zitadel.user.v2.NotificationType.
 */
export const NotificationTypeSchema: GenEnum<NotificationType> = /*@__PURE__*/
  enumDesc(file_zitadel_user_v2_password, 0);

