// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/pat.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { IDFilter, TimestampFilter } from "../../filter/v2/filter_pb";
import { file_zitadel_filter_v2_filter } from "../../filter/v2/filter_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/pat.proto.
 */
export const file_zitadel_user_v2_pat: GenFile = /*@__PURE__*/
  fileDesc("Chl6aXRhZGVsL3VzZXIvdjIvcGF0LnByb3RvEg96aXRhZGVsLnVzZXIudjIi5AEKE1BlcnNvbmFsQWNjZXNzVG9rZW4SMQoNY3JlYXRpb25fZGF0ZRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoLY2hhbmdlX2RhdGUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgoKAmlkGAMgASgJEg8KB3VzZXJfaWQYBCABKAkSFwoPb3JnYW5pemF0aW9uX2lkGAUgASgJEjMKD2V4cGlyYXRpb25fZGF0ZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAi4wIKIFBlcnNvbmFsQWNjZXNzVG9rZW5zU2VhcmNoRmlsdGVyEjYKD3Rva2VuX2lkX2ZpbHRlchgBIAEoCzIbLnppdGFkZWwuZmlsdGVyLnYyLklERmlsdGVySAASNQoOdXNlcl9pZF9maWx0ZXIYAiABKAsyGy56aXRhZGVsLmZpbHRlci52Mi5JREZpbHRlckgAEj0KFm9yZ2FuaXphdGlvbl9pZF9maWx0ZXIYAyABKAsyGy56aXRhZGVsLmZpbHRlci52Mi5JREZpbHRlckgAEkEKE2NyZWF0ZWRfZGF0ZV9maWx0ZXIYBCABKAsyIi56aXRhZGVsLmZpbHRlci52Mi5UaW1lc3RhbXBGaWx0ZXJIABJEChZleHBpcmF0aW9uX2RhdGVfZmlsdGVyGAUgASgLMiIueml0YWRlbC5maWx0ZXIudjIuVGltZXN0YW1wRmlsdGVySABCCAoGZmlsdGVyKsYCChxQZXJzb25hbEFjY2Vzc1Rva2VuRmllbGROYW1lEjAKLFBFUlNPTkFMX0FDQ0VTU19UT0tFTl9GSUVMRF9OQU1FX1VOU1BFQ0lGSUVEEAASMQotUEVSU09OQUxfQUNDRVNTX1RPS0VOX0ZJRUxEX05BTUVfQ1JFQVRFRF9EQVRFEAESJwojUEVSU09OQUxfQUNDRVNTX1RPS0VOX0ZJRUxEX05BTUVfSUQQAhIsCihQRVJTT05BTF9BQ0NFU1NfVE9LRU5fRklFTERfTkFNRV9VU0VSX0lEEAMSNAowUEVSU09OQUxfQUNDRVNTX1RPS0VOX0ZJRUxEX05BTUVfT1JHQU5JWkFUSU9OX0lEEAQSNAowUEVSU09OQUxfQUNDRVNTX1RPS0VOX0ZJRUxEX05BTUVfRVhQSVJBVElPTl9EQVRFEAViBnByb3RvMw", [file_google_protobuf_timestamp, file_zitadel_filter_v2_filter]);

/**
 * @generated from message zitadel.user.v2.PersonalAccessToken
 */
export type PersonalAccessToken = Message<"zitadel.user.v2.PersonalAccessToken"> & {
  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 1;
   */
  creationDate?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: Timestamp | undefined;

  /**
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;

  /**
   * @generated from field: string organization_id = 5;
   */
  organizationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp expiration_date = 6;
   */
  expirationDate?: Timestamp | undefined;
};

/**
 * Describes the message zitadel.user.v2.PersonalAccessToken.
 * Use `create(PersonalAccessTokenSchema)` to create a new message.
 */
export const PersonalAccessTokenSchema: GenMessage<PersonalAccessToken> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_pat, 0);

/**
 * @generated from message zitadel.user.v2.PersonalAccessTokensSearchFilter
 */
export type PersonalAccessTokensSearchFilter = Message<"zitadel.user.v2.PersonalAccessTokensSearchFilter"> & {
  /**
   * @generated from oneof zitadel.user.v2.PersonalAccessTokensSearchFilter.filter
   */
  filter: {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter token_id_filter = 1;
     */
    value: IDFilter;
    case: "tokenIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter user_id_filter = 2;
     */
    value: IDFilter;
    case: "userIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.IDFilter organization_id_filter = 3;
     */
    value: IDFilter;
    case: "organizationIdFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.TimestampFilter created_date_filter = 4;
     */
    value: TimestampFilter;
    case: "createdDateFilter";
  } | {
    /**
     * @generated from field: zitadel.filter.v2.TimestampFilter expiration_date_filter = 5;
     */
    value: TimestampFilter;
    case: "expirationDateFilter";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.user.v2.PersonalAccessTokensSearchFilter.
 * Use `create(PersonalAccessTokensSearchFilterSchema)` to create a new message.
 */
export const PersonalAccessTokensSearchFilterSchema: GenMessage<PersonalAccessTokensSearchFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_pat, 1);

/**
 * @generated from enum zitadel.user.v2.PersonalAccessTokenFieldName
 */
export enum PersonalAccessTokenFieldName {
  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE = 1;
   */
  CREATED_DATE = 1,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID = 2;
   */
  ID = 2,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID = 3;
   */
  USER_ID = 3,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID = 4;
   */
  ORGANIZATION_ID = 4,

  /**
   * @generated from enum value: PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE = 5;
   */
  EXPIRATION_DATE = 5,
}

/**
 * Describes the enum zitadel.user.v2.PersonalAccessTokenFieldName.
 */
export const PersonalAccessTokenFieldNameSchema: GenEnum<PersonalAccessTokenFieldName> = /*@__PURE__*/
  enumDesc(file_zitadel_user_v2_pat, 0);

