// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/user/v2/phone.proto (package zitadel.user.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/user/v2/phone.proto.
 */
export const file_zitadel_user_v2_phone: GenFile = /*@__PURE__*/
  fileDesc("Cht6aXRhZGVsL3VzZXIvdjIvcGhvbmUucHJvdG8SD3ppdGFkZWwudXNlci52MiLLAQoNU2V0SHVtYW5QaG9uZRINCgVwaG9uZRgBIAEoCRI/CglzZW5kX2NvZGUYAiABKAsyKi56aXRhZGVsLnVzZXIudjIuU2VuZFBob25lVmVyaWZpY2F0aW9uQ29kZUgAEkMKC3JldHVybl9jb2RlGAMgASgLMiwueml0YWRlbC51c2VyLnYyLlJldHVyblBob25lVmVyaWZpY2F0aW9uQ29kZUgAEhUKC2lzX3ZlcmlmaWVkGAQgASgISABCDgoMdmVyaWZpY2F0aW9uIjAKCkh1bWFuUGhvbmUSDQoFcGhvbmUYASABKAkSEwoLaXNfdmVyaWZpZWQYAiABKAgiGwoZU2VuZFBob25lVmVyaWZpY2F0aW9uQ29kZSIdChtSZXR1cm5QaG9uZVZlcmlmaWNhdGlvbkNvZGViBnByb3RvMw");

/**
 * @generated from message zitadel.user.v2.SetHumanPhone
 */
export type SetHumanPhone = Message<"zitadel.user.v2.SetHumanPhone"> & {
  /**
   * @generated from field: string phone = 1;
   */
  phone: string;

  /**
   * @generated from oneof zitadel.user.v2.SetHumanPhone.verification
   */
  verification: {
    /**
     * @generated from field: zitadel.user.v2.SendPhoneVerificationCode send_code = 2;
     */
    value: SendPhoneVerificationCode;
    case: "sendCode";
  } | {
    /**
     * @generated from field: zitadel.user.v2.ReturnPhoneVerificationCode return_code = 3;
     */
    value: ReturnPhoneVerificationCode;
    case: "returnCode";
  } | {
    /**
     * @generated from field: bool is_verified = 4;
     */
    value: boolean;
    case: "isVerified";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.user.v2.SetHumanPhone.
 * Use `create(SetHumanPhoneSchema)` to create a new message.
 */
export const SetHumanPhoneSchema: GenMessage<SetHumanPhone> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_phone, 0);

/**
 * @generated from message zitadel.user.v2.HumanPhone
 */
export type HumanPhone = Message<"zitadel.user.v2.HumanPhone"> & {
  /**
   * @generated from field: string phone = 1;
   */
  phone: string;

  /**
   * @generated from field: bool is_verified = 2;
   */
  isVerified: boolean;
};

/**
 * Describes the message zitadel.user.v2.HumanPhone.
 * Use `create(HumanPhoneSchema)` to create a new message.
 */
export const HumanPhoneSchema: GenMessage<HumanPhone> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_phone, 1);

/**
 * @generated from message zitadel.user.v2.SendPhoneVerificationCode
 */
export type SendPhoneVerificationCode = Message<"zitadel.user.v2.SendPhoneVerificationCode"> & {
};

/**
 * Describes the message zitadel.user.v2.SendPhoneVerificationCode.
 * Use `create(SendPhoneVerificationCodeSchema)` to create a new message.
 */
export const SendPhoneVerificationCodeSchema: GenMessage<SendPhoneVerificationCode> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_phone, 2);

/**
 * @generated from message zitadel.user.v2.ReturnPhoneVerificationCode
 */
export type ReturnPhoneVerificationCode = Message<"zitadel.user.v2.ReturnPhoneVerificationCode"> & {
};

/**
 * Describes the message zitadel.user.v2.ReturnPhoneVerificationCode.
 * Use `create(ReturnPhoneVerificationCodeSchema)` to create a new message.
 */
export const ReturnPhoneVerificationCodeSchema: GenMessage<ReturnPhoneVerificationCode> = /*@__PURE__*/
  messageDesc(file_zitadel_user_v2_phone, 3);

