// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/session/v2/challenge.proto (package zitadel.session.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/session/v2/challenge.proto.
 */
export const file_zitadel_session_v2_challenge: GenFile = /*@__PURE__*/
  fileDesc("CiJ6aXRhZGVsL3Nlc3Npb24vdjIvY2hhbGxlbmdlLnByb3RvEhJ6aXRhZGVsLnNlc3Npb24udjIiqAUKEVJlcXVlc3RDaGFsbGVuZ2VzEkcKCndlYl9hdXRoX24YASABKAsyLi56aXRhZGVsLnNlc3Npb24udjIuUmVxdWVzdENoYWxsZW5nZXMuV2ViQXV0aE5IAIgBARJCCgdvdHBfc21zGAIgASgLMiwueml0YWRlbC5zZXNzaW9uLnYyLlJlcXVlc3RDaGFsbGVuZ2VzLk9UUFNNU0gBiAEBEkYKCW90cF9lbWFpbBgDIAEoCzIuLnppdGFkZWwuc2Vzc2lvbi52Mi5SZXF1ZXN0Q2hhbGxlbmdlcy5PVFBFbWFpbEgCiAEBGnIKCFdlYkF1dGhOEg4KBmRvbWFpbhgBIAEoCRJWCh11c2VyX3ZlcmlmaWNhdGlvbl9yZXF1aXJlbWVudBgCIAEoDjIvLnppdGFkZWwuc2Vzc2lvbi52Mi5Vc2VyVmVyaWZpY2F0aW9uUmVxdWlyZW1lbnQaHQoGT1RQU01TEhMKC3JldHVybl9jb2RlGAEgASgIGoECCghPVFBFbWFpbBJMCglzZW5kX2NvZGUYAiABKAsyNy56aXRhZGVsLnNlc3Npb24udjIuUmVxdWVzdENoYWxsZW5nZXMuT1RQRW1haWwuU2VuZENvZGVIABJQCgtyZXR1cm5fY29kZRgDIAEoCzI5LnppdGFkZWwuc2Vzc2lvbi52Mi5SZXF1ZXN0Q2hhbGxlbmdlcy5PVFBFbWFpbC5SZXR1cm5Db2RlSAAaNgoIU2VuZENvZGUSGQoMdXJsX3RlbXBsYXRlGAEgASgJSACIAQFCDwoNX3VybF90ZW1wbGF0ZRoMCgpSZXR1cm5Db2RlQg8KDWRlbGl2ZXJ5X3R5cGVCDQoLX3dlYl9hdXRoX25CCgoIX290cF9zbXNCDAoKX290cF9lbWFpbCL5AQoKQ2hhbGxlbmdlcxJACgp3ZWJfYXV0aF9uGAEgASgLMicueml0YWRlbC5zZXNzaW9uLnYyLkNoYWxsZW5nZXMuV2ViQXV0aE5IAIgBARIUCgdvdHBfc21zGAIgASgJSAGIAQESFgoJb3RwX2VtYWlsGAMgASgJSAKIAQEaUgoIV2ViQXV0aE4SRgolcHVibGljX2tleV9jcmVkZW50aWFsX3JlcXVlc3Rfb3B0aW9ucxgBIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCDQoLX3dlYl9hdXRoX25CCgoIX290cF9zbXNCDAoKX290cF9lbWFpbCrUAQobVXNlclZlcmlmaWNhdGlvblJlcXVpcmVtZW50Ei0KKVVTRVJfVkVSSUZJQ0FUSU9OX1JFUVVJUkVNRU5UX1VOU1BFQ0lGSUVEEAASKgomVVNFUl9WRVJJRklDQVRJT05fUkVRVUlSRU1FTlRfUkVRVUlSRUQQARIrCidVU0VSX1ZFUklGSUNBVElPTl9SRVFVSVJFTUVOVF9QUkVGRVJSRUQQAhItCilVU0VSX1ZFUklGSUNBVElPTl9SRVFVSVJFTUVOVF9ESVNDT1VSQUdFRBADYgZwcm90bzM", [file_google_protobuf_struct]);

/**
 * @generated from message zitadel.session.v2.RequestChallenges
 */
export type RequestChallenges = Message<"zitadel.session.v2.RequestChallenges"> & {
  /**
   * @generated from field: optional zitadel.session.v2.RequestChallenges.WebAuthN web_auth_n = 1;
   */
  webAuthN?: RequestChallenges_WebAuthN | undefined;

  /**
   * @generated from field: optional zitadel.session.v2.RequestChallenges.OTPSMS otp_sms = 2;
   */
  otpSms?: RequestChallenges_OTPSMS | undefined;

  /**
   * @generated from field: optional zitadel.session.v2.RequestChallenges.OTPEmail otp_email = 3;
   */
  otpEmail?: RequestChallenges_OTPEmail | undefined;
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.
 * Use `create(RequestChallengesSchema)` to create a new message.
 */
export const RequestChallengesSchema: GenMessage<RequestChallenges> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0);

/**
 * @generated from message zitadel.session.v2.RequestChallenges.WebAuthN
 */
export type RequestChallenges_WebAuthN = Message<"zitadel.session.v2.RequestChallenges.WebAuthN"> & {
  /**
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * @generated from field: zitadel.session.v2.UserVerificationRequirement user_verification_requirement = 2;
   */
  userVerificationRequirement: UserVerificationRequirement;
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.WebAuthN.
 * Use `create(RequestChallenges_WebAuthNSchema)` to create a new message.
 */
export const RequestChallenges_WebAuthNSchema: GenMessage<RequestChallenges_WebAuthN> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0, 0);

/**
 * @generated from message zitadel.session.v2.RequestChallenges.OTPSMS
 */
export type RequestChallenges_OTPSMS = Message<"zitadel.session.v2.RequestChallenges.OTPSMS"> & {
  /**
   * @generated from field: bool return_code = 1;
   */
  returnCode: boolean;
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.OTPSMS.
 * Use `create(RequestChallenges_OTPSMSSchema)` to create a new message.
 */
export const RequestChallenges_OTPSMSSchema: GenMessage<RequestChallenges_OTPSMS> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0, 1);

/**
 * @generated from message zitadel.session.v2.RequestChallenges.OTPEmail
 */
export type RequestChallenges_OTPEmail = Message<"zitadel.session.v2.RequestChallenges.OTPEmail"> & {
  /**
   * @generated from oneof zitadel.session.v2.RequestChallenges.OTPEmail.delivery_type
   */
  deliveryType: {
    /**
     * @generated from field: zitadel.session.v2.RequestChallenges.OTPEmail.SendCode send_code = 2;
     */
    value: RequestChallenges_OTPEmail_SendCode;
    case: "sendCode";
  } | {
    /**
     * @generated from field: zitadel.session.v2.RequestChallenges.OTPEmail.ReturnCode return_code = 3;
     */
    value: RequestChallenges_OTPEmail_ReturnCode;
    case: "returnCode";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.OTPEmail.
 * Use `create(RequestChallenges_OTPEmailSchema)` to create a new message.
 */
export const RequestChallenges_OTPEmailSchema: GenMessage<RequestChallenges_OTPEmail> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0, 2);

/**
 * @generated from message zitadel.session.v2.RequestChallenges.OTPEmail.SendCode
 */
export type RequestChallenges_OTPEmail_SendCode = Message<"zitadel.session.v2.RequestChallenges.OTPEmail.SendCode"> & {
  /**
   * @generated from field: optional string url_template = 1;
   */
  urlTemplate?: string | undefined;
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.OTPEmail.SendCode.
 * Use `create(RequestChallenges_OTPEmail_SendCodeSchema)` to create a new message.
 */
export const RequestChallenges_OTPEmail_SendCodeSchema: GenMessage<RequestChallenges_OTPEmail_SendCode> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0, 2, 0);

/**
 * @generated from message zitadel.session.v2.RequestChallenges.OTPEmail.ReturnCode
 */
export type RequestChallenges_OTPEmail_ReturnCode = Message<"zitadel.session.v2.RequestChallenges.OTPEmail.ReturnCode"> & {
};

/**
 * Describes the message zitadel.session.v2.RequestChallenges.OTPEmail.ReturnCode.
 * Use `create(RequestChallenges_OTPEmail_ReturnCodeSchema)` to create a new message.
 */
export const RequestChallenges_OTPEmail_ReturnCodeSchema: GenMessage<RequestChallenges_OTPEmail_ReturnCode> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 0, 2, 1);

/**
 * @generated from message zitadel.session.v2.Challenges
 */
export type Challenges = Message<"zitadel.session.v2.Challenges"> & {
  /**
   * @generated from field: optional zitadel.session.v2.Challenges.WebAuthN web_auth_n = 1;
   */
  webAuthN?: Challenges_WebAuthN | undefined;

  /**
   * @generated from field: optional string otp_sms = 2;
   */
  otpSms?: string | undefined;

  /**
   * @generated from field: optional string otp_email = 3;
   */
  otpEmail?: string | undefined;
};

/**
 * Describes the message zitadel.session.v2.Challenges.
 * Use `create(ChallengesSchema)` to create a new message.
 */
export const ChallengesSchema: GenMessage<Challenges> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 1);

/**
 * @generated from message zitadel.session.v2.Challenges.WebAuthN
 */
export type Challenges_WebAuthN = Message<"zitadel.session.v2.Challenges.WebAuthN"> & {
  /**
   * @generated from field: google.protobuf.Struct public_key_credential_request_options = 1;
   */
  publicKeyCredentialRequestOptions?: JsonObject | undefined;
};

/**
 * Describes the message zitadel.session.v2.Challenges.WebAuthN.
 * Use `create(Challenges_WebAuthNSchema)` to create a new message.
 */
export const Challenges_WebAuthNSchema: GenMessage<Challenges_WebAuthN> = /*@__PURE__*/
  messageDesc(file_zitadel_session_v2_challenge, 1, 0);

/**
 * @generated from enum zitadel.session.v2.UserVerificationRequirement
 */
export enum UserVerificationRequirement {
  /**
   * @generated from enum value: USER_VERIFICATION_REQUIREMENT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_VERIFICATION_REQUIREMENT_REQUIRED = 1;
   */
  REQUIRED = 1,

  /**
   * @generated from enum value: USER_VERIFICATION_REQUIREMENT_PREFERRED = 2;
   */
  PREFERRED = 2,

  /**
   * @generated from enum value: USER_VERIFICATION_REQUIREMENT_DISCOURAGED = 3;
   */
  DISCOURAGED = 3,
}

/**
 * Describes the enum zitadel.session.v2.UserVerificationRequirement.
 */
export const UserVerificationRequirementSchema: GenEnum<UserVerificationRequirement> = /*@__PURE__*/
  enumDesc(file_zitadel_session_v2_challenge, 0);

