// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/filter/v2/filter.proto (package zitadel.filter.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/filter/v2/filter.proto.
 */
export const file_zitadel_filter_v2_filter: GenFile = /*@__PURE__*/
  fileDesc("Ch56aXRhZGVsL2ZpbHRlci92Mi9maWx0ZXIucHJvdG8SEXppdGFkZWwuZmlsdGVyLnYyIj8KEVBhZ2luYXRpb25SZXF1ZXN0Eg4KBm9mZnNldBgBIAEoBBINCgVsaW1pdBgCIAEoDRILCgNhc2MYAyABKAgiQQoSUGFnaW5hdGlvblJlc3BvbnNlEhQKDHRvdGFsX3Jlc3VsdBgBIAEoBBIVCg1hcHBsaWVkX2xpbWl0GAIgASgEIhYKCElERmlsdGVyEgoKAmlkGAEgASgJInoKD1RpbWVzdGFtcEZpbHRlchItCgl0aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjgKBm1ldGhvZBgCIAEoDjIoLnppdGFkZWwuZmlsdGVyLnYyLlRpbWVzdGFtcEZpbHRlck1ldGhvZCIaCgtJbklEc0ZpbHRlchILCgNpZHMYASADKAkqzgIKEFRleHRGaWx0ZXJNZXRob2QSHQoZVEVYVF9GSUxURVJfTUVUSE9EX0VRVUFMUxAAEikKJVRFWFRfRklMVEVSX01FVEhPRF9FUVVBTFNfSUdOT1JFX0NBU0UQARIiCh5URVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEgQAhIuCipURVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEhfSUdOT1JFX0NBU0UQAxIfChtURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlMQBBIrCidURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlNfSUdOT1JFX0NBU0UQBRIgChxURVhUX0ZJTFRFUl9NRVRIT0RfRU5EU19XSVRIEAYSLAooVEVYVF9GSUxURVJfTUVUSE9EX0VORFNfV0lUSF9JR05PUkVfQ0FTRRAHKi0KEExpc3RGaWx0ZXJNZXRob2QSGQoVTElTVF9GSUxURVJfTUVUSE9EX0lOEAAq3QEKFVRpbWVzdGFtcEZpbHRlck1ldGhvZBIiCh5USU1FU1RBTVBfRklMVEVSX01FVEhPRF9FUVVBTFMQABIhCh1USU1FU1RBTVBfRklMVEVSX01FVEhPRF9BRlRFUhABEisKJ1RJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0FGVEVSX09SX0VRVUFMUxACEiIKHlRJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0JFRk9SRRADEiwKKFRJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0JFRk9SRV9PUl9FUVVBTFMQBCpUChBCeXRlRmlsdGVyTWV0aG9kEh0KGUJZVEVfRklMVEVSX01FVEhPRF9FUVVBTFMQABIhCh1CWVRFX0ZJTFRFUl9NRVRIT0RfTk9UX0VRVUFMUxABYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message zitadel.filter.v2.PaginationRequest
 */
export type PaginationRequest = Message<"zitadel.filter.v2.PaginationRequest"> & {
  /**
   * @generated from field: uint64 offset = 1;
   */
  offset: bigint;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: bool asc = 3;
   */
  asc: boolean;
};

/**
 * Describes the message zitadel.filter.v2.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 0);

/**
 * @generated from message zitadel.filter.v2.PaginationResponse
 */
export type PaginationResponse = Message<"zitadel.filter.v2.PaginationResponse"> & {
  /**
   * @generated from field: uint64 total_result = 1;
   */
  totalResult: bigint;

  /**
   * @generated from field: uint64 applied_limit = 2;
   */
  appliedLimit: bigint;
};

/**
 * Describes the message zitadel.filter.v2.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 1);

/**
 * @generated from message zitadel.filter.v2.IDFilter
 */
export type IDFilter = Message<"zitadel.filter.v2.IDFilter"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zitadel.filter.v2.IDFilter.
 * Use `create(IDFilterSchema)` to create a new message.
 */
export const IDFilterSchema: GenMessage<IDFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 2);

/**
 * @generated from message zitadel.filter.v2.TimestampFilter
 */
export type TimestampFilter = Message<"zitadel.filter.v2.TimestampFilter"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: zitadel.filter.v2.TimestampFilterMethod method = 2;
   */
  method: TimestampFilterMethod;
};

/**
 * Describes the message zitadel.filter.v2.TimestampFilter.
 * Use `create(TimestampFilterSchema)` to create a new message.
 */
export const TimestampFilterSchema: GenMessage<TimestampFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 3);

/**
 * @generated from message zitadel.filter.v2.InIDsFilter
 */
export type InIDsFilter = Message<"zitadel.filter.v2.InIDsFilter"> & {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[];
};

/**
 * Describes the message zitadel.filter.v2.InIDsFilter.
 * Use `create(InIDsFilterSchema)` to create a new message.
 */
export const InIDsFilterSchema: GenMessage<InIDsFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 4);

/**
 * @generated from enum zitadel.filter.v2.TextFilterMethod
 */
export enum TextFilterMethod {
  /**
   * @generated from enum value: TEXT_FILTER_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE = 1;
   */
  EQUALS_IGNORE_CASE = 1,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_STARTS_WITH = 2;
   */
  STARTS_WITH = 2,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE = 3;
   */
  STARTS_WITH_IGNORE_CASE = 3,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_CONTAINS = 4;
   */
  CONTAINS = 4,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE = 5;
   */
  CONTAINS_IGNORE_CASE = 5,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_ENDS_WITH = 6;
   */
  ENDS_WITH = 6,

  /**
   * @generated from enum value: TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE = 7;
   */
  ENDS_WITH_IGNORE_CASE = 7,
}

/**
 * Describes the enum zitadel.filter.v2.TextFilterMethod.
 */
export const TextFilterMethodSchema: GenEnum<TextFilterMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 0);

/**
 * @generated from enum zitadel.filter.v2.ListFilterMethod
 */
export enum ListFilterMethod {
  /**
   * @generated from enum value: LIST_FILTER_METHOD_IN = 0;
   */
  IN = 0,
}

/**
 * Describes the enum zitadel.filter.v2.ListFilterMethod.
 */
export const ListFilterMethodSchema: GenEnum<ListFilterMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 1);

/**
 * @generated from enum zitadel.filter.v2.TimestampFilterMethod
 */
export enum TimestampFilterMethod {
  /**
   * @generated from enum value: TIMESTAMP_FILTER_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: TIMESTAMP_FILTER_METHOD_AFTER = 1;
   */
  AFTER = 1,

  /**
   * @generated from enum value: TIMESTAMP_FILTER_METHOD_AFTER_OR_EQUALS = 2;
   */
  AFTER_OR_EQUALS = 2,

  /**
   * @generated from enum value: TIMESTAMP_FILTER_METHOD_BEFORE = 3;
   */
  BEFORE = 3,

  /**
   * @generated from enum value: TIMESTAMP_FILTER_METHOD_BEFORE_OR_EQUALS = 4;
   */
  BEFORE_OR_EQUALS = 4,
}

/**
 * Describes the enum zitadel.filter.v2.TimestampFilterMethod.
 */
export const TimestampFilterMethodSchema: GenEnum<TimestampFilterMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 2);

/**
 * @generated from enum zitadel.filter.v2.ByteFilterMethod
 */
export enum ByteFilterMethod {
  /**
   * @generated from enum value: BYTE_FILTER_METHOD_EQUALS = 0;
   */
  EQUALS = 0,

  /**
   * @generated from enum value: BYTE_FILTER_METHOD_NOT_EQUALS = 1;
   */
  NOT_EQUALS = 1,
}

/**
 * Describes the enum zitadel.filter.v2.ByteFilterMethod.
 */
export const ByteFilterMethodSchema: GenEnum<ByteFilterMethod> = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 3);

