/**
 * proto-generate — regenerate the Zitadel v2 protobuf client in `server/lib/zitadel/proto/`.
 *
 * The .proto files are read straight from the zitadel repository at the pinned release tag
 * (`ZITADEL_VERSION`), so no protos are vendored. Only the v2 services the login uses are
 * generated (plus their imports). Bump `ZITADEL_VERSION` together with the Zitadel server and the
 * login source it is ported from, then run `bun run proto:generate`.
 *
 * Never hand-edit the generated `*_pb.ts` files.
 */
import { existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import path from "path";

const ZITADEL_VERSION = "v4.19.2";

const OUT_DIR = "server/lib/zitadel/proto";

const PROTO_PATHS = [
	"zitadel/idp/v2",
	"zitadel/internal_permission/v2",
	"zitadel/message.proto",
	"zitadel/oidc/v2",
	"zitadel/org/v2",
	"zitadel/saml/v2",
	"zitadel/session/v2",
	"zitadel/settings/v2",
	"zitadel/user/v2",
];

const TEMP_DIR = "./data/proto-generate";
const TEMPLATE_PATH = path.join(TEMP_DIR, "buf.gen.yaml");

const template = `version: v2
managed:
  enabled: true
plugins:
  - local: ["bun", "./node_modules/@bufbuild/protoc-gen-es/bin/protoc-gen-es"]
    out: ${OUT_DIR}
    include_imports: true
    opt:
      - target=ts
      - import_extension=none
`;

try {
	if (!existsSync(TEMP_DIR)) {
		mkdirSync(TEMP_DIR, { recursive: true });
	}
	writeFileSync(TEMPLATE_PATH, template);

	rmSync(OUT_DIR, { recursive: true, force: true });

	const input = `https://github.com/zitadel/zitadel.git#tag=${ZITADEL_VERSION},subdir=proto,depth=1`;
	const pathArgs = PROTO_PATHS.flatMap((p) => ["--path", p]);

	console.log(`[proto-generate] Generating Zitadel ${ZITADEL_VERSION} protos into ${OUT_DIR} ...`);
	await Bun.$`bunx --bun buf generate ${input} --template ${TEMPLATE_PATH} ${pathArgs}`;

	writeFileSync(
		path.join(OUT_DIR, "README.md"),
		`# Generated Zitadel protos\n\nGenerated by \`bun run proto:generate\` from zitadel \`${ZITADEL_VERSION}\`. Do not edit.\n`,
	);

	rmSync(TEMP_DIR, { recursive: true, force: true });
	console.log("[proto-generate] Done.");
} catch (err: any) {
	console.error("[proto-generate] Failed to generate protos:", err?.stderr?.toString?.() ?? err);
	rmSync(TEMP_DIR, { recursive: true, force: true });
	process.exit(1);
}
