// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetSettingsBrandingQuery = z.object({
    organization: z.string().optional(),
    fallbackToDefault: z.enum(['true', 'false']).optional()
});

/**
 * Branding loaded
 */
export const zGetSettingsBrandingResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Branding loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        defaultOrganization: z.string().optional()
    })
});

export const zGetSettingsI18nQuery = z.object({
    organization: z.string().optional()
});

/**
 * Translations loaded
 */
export const zGetSettingsI18nResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Translations loaded'),
    data: z.object({
        locale: z.string(),
        languages: z.array(z.object({
            code: z.string(),
            name: z.string()
        })),
        messages: z.record(z.string(), z.unknown())
    })
});

export const zPutSettingsLanguageBody = z.object({
    language: z.string().min(2).max(10)
});

/**
 * Language updated
 */
export const zPutSettingsLanguageResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Language updated'),
    data: z.null()
});

export const zGetLoginnameQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    orgDomain: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetLoginnameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        identityProviders: z.array(z.object({
            id: z.string(),
            name: z.string(),
            type: z.enum([
                'github',
                'github_es',
                'gitlab',
                'gitlab_es',
                'apple',
                'google',
                'azure',
                'saml',
                'oauth',
                'oidc',
                'ldap',
                'jwt',
                'zitadel'
            ])
        })),
        defaultOrganization: z.string().optional(),
        idpLoginHint: z.string().optional()
    })
});

export const zPostLoginnameBody = z.object({
    loginName: z.string().min(1),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    defaultOrganization: z.string().optional(),
    suffix: z.string().optional()
});

/**
 * Next step resolved
 */
export const zPostLoginnameResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Next step resolved'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetAccountsQuery = z.object({
    requestId: z.string().optional(),
    organization: z.string().optional(),
    orgDomain: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetAccountsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        sessions: z.array(z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }))
    })
});

export const zGetPasswordQuery = z.object({
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        defaultOrganization: z.string().optional(),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable()
    })
});

export const zPostPasswordBody = z.object({
    loginName: z.string().min(1),
    password: z.string().min(1),
    organization: z.string().optional(),
    defaultOrganization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Password verified
 */
export const zPostPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password verified'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zPostPasswordResetBody = z.object({
    loginName: z.string().min(1),
    organization: z.string().optional(),
    defaultOrganization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Password reset requested
 */
export const zPostPasswordResetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password reset requested'),
    data: z.null()
});

export const zGetPasswordSetQuery = z.object({
    userId: z.string().optional(),
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional(),
    code: z.string().optional(),
    initial: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetPasswordSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        error: z.enum(['couldNotGetLoginSettings']).optional(),
        defaultOrganization: z.string().optional(),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        passwordComplexity: z.object({
            minLength: z.number(),
            requiresUppercase: z.boolean(),
            requiresLowercase: z.boolean(),
            requiresNumber: z.boolean(),
            requiresSymbol: z.boolean()
        }).nullable(),
        form: z.object({
            userId: z.string(),
            loginName: z.string(),
            codeRequired: z.boolean()
        }).nullable()
    })
});

export const zPostPasswordSetBody = z.object({
    userId: z.string().min(1),
    password: z.string().min(1),
    code: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Password set
 */
export const zPostPasswordSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password set'),
    data: z.null()
});

export const zGetPasswordChangeQuery = z.object({
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetPasswordChangeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        passwordComplexity: z.object({
            minLength: z.number(),
            requiresUppercase: z.boolean(),
            requiresLowercase: z.boolean(),
            requiresNumber: z.boolean(),
            requiresSymbol: z.boolean()
        }).nullable()
    })
});

export const zPostPasswordChangeBody = z.object({
    sessionId: z.string().min(1),
    currentPassword: z.string().min(1),
    password: z.string().min(1)
});

/**
 * Password changed
 */
export const zPostPasswordChangeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Password changed'),
    data: z.null()
});

export const zGetPasskeyQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetPasskeyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable()
    })
});

export const zPostPasskeyBody = z.object({
    loginName: z.string().optional(),
    sessionId: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional(),
    credentialAssertionData: z.record(z.string(), z.unknown())
});

/**
 * Passkey verified
 */
export const zPostPasskeyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Passkey verified'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetPasskeySetQuery = z.object({
    userId: z.string().optional(),
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetPasskeySetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        user: z.object({
            loginName: z.string(),
            displayName: z.string().optional()
        }).nullable()
    })
});

export const zPostPasskeyRegistrationBody = z.object({
    sessionId: z.string().optional(),
    userId: z.string().optional(),
    code: z.string().optional(),
    codeId: z.string().optional()
});

/**
 * Passkey registration started
 */
export const zPostPasskeyRegistrationResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Passkey registration started'),
    data: z.object({
        passkeyId: z.string(),
        publicKeyCredentialCreationOptions: z.record(z.string(), z.unknown())
    })
});

export const zPostPasskeyRegistrationVerifyBody = z.object({
    passkeyId: z.string().min(1),
    passkeyName: z.string().optional(),
    publicKeyCredential: z.record(z.string(), z.unknown()),
    sessionId: z.string().optional(),
    userId: z.string().optional()
});

/**
 * Passkey registered
 */
export const zPostPasskeyRegistrationVerifyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Passkey registered'),
    data: z.object({
        loginName: z.string().optional()
    })
});

export const zGetU2fQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    sessionId: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetU2fResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable()
    })
});

export const zGetU2fSetQuery = z.object({
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetU2fSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        enrollmentAuthorized: z.boolean(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable()
    })
});

export const zPostU2fRegistrationBody = z.object({
    sessionId: z.string().min(1)
});

/**
 * Security key registration started
 */
export const zPostU2fRegistrationResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Security key registration started'),
    data: z.object({
        u2fId: z.string(),
        publicKeyCredentialCreationOptions: z.record(z.string(), z.unknown())
    })
});

export const zPostU2fRegistrationVerifyBody = z.object({
    u2fId: z.string().min(1),
    passkeyName: z.string().optional(),
    publicKeyCredential: z.record(z.string(), z.unknown()),
    sessionId: z.string().min(1)
});

/**
 * Security key registered
 */
export const zPostU2fRegistrationVerifyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Security key registered'),
    data: z.null()
});

export const zPostOtpTotpVerifyBody = z.object({
    code: z.string().min(1),
    loginName: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Authenticator app verified
 */
export const zPostOtpTotpVerifyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Authenticator app verified'),
    data: z.null()
});

export const zGetOtpByMethodPath = z.object({
    method: z.enum([
        'time-based',
        'sms',
        'email'
    ])
});

export const zGetOtpByMethodQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    sessionId: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetOtpByMethodResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable()
    })
});

export const zPostOtpByMethodSetBody = z.object({
    loginName: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional(),
    requestId: z.string().optional(),
    checkAfter: z.boolean().optional()
});

export const zPostOtpByMethodSetPath = z.object({
    method: z.enum([
        'time-based',
        'sms',
        'email'
    ])
});

/**
 * OTP setup started
 */
export const zPostOtpByMethodSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('OTP setup started'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        totp: z.object({
            uri: z.string(),
            secret: z.string()
        }).optional(),
        error: z.string().optional(),
        continueUrl: z.string(),
        redirect: z.string().optional()
    })
});

export const zGetMfaQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetMfaResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        authMethods: z.array(z.enum([
            'password',
            'passkey',
            'idp',
            'totp',
            'u2f',
            'otp_sms',
            'otp_email',
            'recovery_code'
        ]))
    })
});

export const zGetMfaSetQuery = z.object({
    loginName: z.string().optional(),
    force: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetMfaSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        valid: z.boolean(),
        authMethods: z.array(z.enum([
            'password',
            'passkey',
            'idp',
            'totp',
            'u2f',
            'otp_sms',
            'otp_email',
            'recovery_code'
        ])),
        phoneVerified: z.boolean(),
        emailVerified: z.boolean(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        redirect: z.string().optional()
    })
});

export const zPostMfaSkipBody = z.object({
    userId: z.string().min(1),
    loginName: z.string().optional(),
    sessionId: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * MFA setup skipped
 */
export const zPostMfaSkipResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('MFA setup skipped'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetAuthenticatorSetQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetAuthenticatorSetResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        error: z.enum(['sessionExpired', 'unknownContext']).optional(),
        redirect: z.string().optional(),
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }).nullable(),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        authMethods: z.array(z.enum([
            'password',
            'passkey',
            'idp',
            'totp',
            'u2f',
            'otp_sms',
            'otp_email',
            'recovery_code'
        ])),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        identityProviders: z.array(z.object({
            id: z.string(),
            name: z.string(),
            type: z.enum([
                'github',
                'github_es',
                'gitlab',
                'gitlab_es',
                'apple',
                'google',
                'azure',
                'saml',
                'oauth',
                'oidc',
                'ldap',
                'jwt',
                'zitadel'
            ])
        })),
        setupParams: z.string()
    })
});

export const zPostSessionBody = z.object({
    loginName: z.string().optional(),
    sessionId: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional(),
    challenges: z.object({
        webAuthN: z.object({
            userVerificationRequirement: z.enum([
                'required',
                'preferred',
                'discouraged'
            ])
        }).optional(),
        otpEmail: z.boolean().optional(),
        otpSms: z.boolean().optional()
    }).optional(),
    checks: z.object({
        totp: z.object({
            code: z.string().min(1)
        }).optional(),
        otpSms: z.object({
            code: z.string().min(1)
        }).optional(),
        otpEmail: z.object({
            code: z.string().min(1)
        }).optional()
    }).optional()
});

/**
 * Session updated
 */
export const zPostSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session updated'),
    data: z.object({
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }),
        challenges: z.object({
            webAuthN: z.object({
                publicKeyCredentialRequestOptions: z.record(z.string(), z.unknown()).optional()
            }).optional()
        }).optional(),
        authMethods: z.array(z.enum([
            'password',
            'passkey',
            'idp',
            'totp',
            'u2f',
            'otp_sms',
            'otp_email',
            'recovery_code'
        ])).optional()
    })
});

export const zPostSessionContinueBody = z.object({
    sessionId: z.string().min(1),
    requestId: z.string().optional()
});

/**
 * Next step resolved
 */
export const zPostSessionContinueResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Next step resolved'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zDeleteSessionBySessionIdPath = z.object({
    sessionId: z.string().min(1)
});

/**
 * Session ended
 */
export const zDeleteSessionBySessionIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session ended'),
    data: z.null()
});

export const zPostFlowCompleteBody = z.object({
    sessionId: z.string().optional(),
    requestId: z.string().optional(),
    loginName: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Flow completed
 */
export const zPostFlowCompleteResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Flow completed'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetRegisterQuery = z.object({
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetRegisterResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        organization: z.string().optional(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        legal: z.object({
            tosLink: z.string(),
            privacyPolicyLink: z.string(),
            helpLink: z.string()
        }).nullable(),
        passwordComplexity: z.object({
            minLength: z.number(),
            requiresUppercase: z.boolean(),
            requiresLowercase: z.boolean(),
            requiresNumber: z.boolean(),
            requiresSymbol: z.boolean()
        }).nullable(),
        identityProviders: z.array(z.object({
            id: z.string(),
            name: z.string(),
            type: z.enum([
                'github',
                'github_es',
                'gitlab',
                'gitlab_es',
                'apple',
                'google',
                'azure',
                'saml',
                'oauth',
                'oidc',
                'ldap',
                'jwt',
                'zitadel'
            ])
        }))
    })
});

export const zPostRegisterBody = z.object({
    email: z.string().min(1),
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    password: z.string().optional(),
    organization: z.string().min(1),
    requestId: z.string().optional()
});

/**
 * User registered
 */
export const zPostRegisterResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User registered'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetRegisterPasswordQuery = z.object({
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetRegisterPasswordResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        organization: z.string().optional(),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        legal: z.object({
            tosLink: z.string(),
            privacyPolicyLink: z.string(),
            helpLink: z.string()
        }).nullable(),
        passwordComplexity: z.object({
            minLength: z.number(),
            requiresUppercase: z.boolean(),
            requiresLowercase: z.boolean(),
            requiresNumber: z.boolean(),
            requiresSymbol: z.boolean()
        }).nullable()
    })
});

export const zPostRegisterIdpBody = z.object({
    email: z.string().min(1),
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    organization: z.string().min(1),
    requestId: z.string().optional(),
    idpIntent: z.object({
        idpIntentId: z.string().min(1),
        idpIntentToken: z.string().min(1)
    }),
    idpUserId: z.string().min(1),
    idpId: z.string().min(1),
    idpUserName: z.string()
});

/**
 * User registered
 */
export const zPostRegisterIdpResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('User registered'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetVerifyQuery = z.object({
    userId: z.string().optional(),
    loginName: z.string().optional(),
    organization: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetVerifyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        avatar: z.object({
            loginName: z.string(),
            displayName: z.string().optional(),
            showDropdown: z.boolean()
        }).nullable(),
        userId: z.string().optional(),
        autoSubmit: z.boolean()
    })
});

export const zPostVerifyBody = z.object({
    userId: z.string().min(1),
    loginName: z.string().optional(),
    organization: z.string().optional(),
    code: z.string().min(1),
    isInvite: z.boolean(),
    requestId: z.string().optional()
});

/**
 * Code verified
 */
export const zPostVerifyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Code verified'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetVerifySuccessQuery = z.object({
    loginName: z.string().optional(),
    organization: z.string().optional(),
    userId: z.string().optional(),
    requestId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetVerifySuccessResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        avatar: z.object({
            loginName: z.string(),
            displayName: z.string().optional(),
            showDropdown: z.boolean()
        }).nullable(),
        continueUrl: z.string().optional()
    })
});

export const zPostVerifyResendBody = z.object({
    userId: z.string().min(1),
    isInvite: z.boolean(),
    requestId: z.string().optional()
});

/**
 * Code sent
 */
export const zPostVerifyResendResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Code sent'),
    data: z.null()
});

export const zGetSignedinQuery = z.object({
    loginName: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetSignedinResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        session: z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        }).nullable(),
        redirectUri: z.string().optional()
    })
});

export const zGetLogoutQuery = z.object({
    organization: z.string().optional(),
    logout_token: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        sessions: z.array(z.object({
            id: z.string(),
            creationDate: z.number().optional(),
            changeDate: z.number().optional(),
            expirationDate: z.number().optional(),
            factors: z.object({
                user: z.object({
                    id: z.string(),
                    loginName: z.string(),
                    displayName: z.string(),
                    organizationId: z.string(),
                    verifiedAt: z.number().optional()
                }).optional(),
                password: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                webAuthN: z.object({
                    verifiedAt: z.number().optional(),
                    userVerified: z.boolean()
                }).optional(),
                intent: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                totp: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpSms: z.object({
                    verifiedAt: z.number().optional()
                }).optional(),
                otpEmail: z.object({
                    verifiedAt: z.number().optional()
                }).optional()
            }).optional()
        })),
        postLogoutRedirectUri: z.string().optional(),
        logoutHint: z.string().optional(),
        organization: z.string().optional()
    })
});

export const zGetDeviceQuery = z.object({
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetDeviceResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        })
    })
});

export const zGetDeviceConsentQuery = z.object({
    user_code: z.string().optional(),
    requestId: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetDeviceConsentResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        error: z.enum(['noUserCode', 'noDeviceRequest']).optional(),
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }).nullable(),
        deviceAuthorizationRequest: z.object({
            id: z.string(),
            appName: z.string(),
            scope: z.array(z.string())
        }).nullable(),
        nextUrl: z.string()
    })
});

export const zPostDeviceCodeBody = z.object({
    userCode: z.string().min(1)
});

/**
 * Device request found
 */
export const zPostDeviceCodeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Device request found'),
    data: z.object({
        deviceAuthorizationRequestId: z.string()
    })
});

export const zPostDeviceDenyBody = z.object({
    deviceAuthorizationId: z.string().min(1)
});

/**
 * Device request denied
 */
export const zPostDeviceDenyResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Device request denied'),
    data: z.null()
});

export const zPostDeviceAuthorizeBody = z.object({
    requestId: z.string().min(1),
    sessionId: z.string().optional(),
    loginName: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Device authorized
 */
export const zPostDeviceAuthorizeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Device authorized'),
    data: z.null()
});

export const zGetIdpQuery = z.object({
    requestId: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetIdpResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        identityProviders: z.array(z.object({
            id: z.string(),
            name: z.string(),
            type: z.enum([
                'github',
                'github_es',
                'gitlab',
                'gitlab_es',
                'apple',
                'google',
                'azure',
                'saml',
                'oauth',
                'oidc',
                'ldap',
                'jwt',
                'zitadel'
            ])
        }))
    })
});

export const zGetIdpLdapQuery = z.object({
    idpId: z.string().optional(),
    organization: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetIdpLdapResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        })
    })
});

export const zPostIdpLdapBody = z.object({
    username: z.string().min(1),
    password: z.string().min(1),
    idpId: z.string().min(1),
    link: z.boolean(),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    postErrorRedirectUrl: z.string().optional(),
    linkToSessionId: z.string().optional(),
    linkFingerprint: z.string().optional()
});

/**
 * LDAP login started
 */
export const zPostIdpLdapResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('LDAP login started'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zGetIdpFailureQuery = z.object({
    organization: z.string().optional(),
    userId: z.string().optional()
});

/**
 * Page data loaded
 */
export const zGetIdpFailureResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Page data loaded'),
    data: z.object({
        branding: z.object({
            logoUrl: z.string().optional(),
            iconUrl: z.string().optional(),
            primaryColor: z.string().optional(),
            hideLoginNameSuffix: z.boolean()
        }),
        loginSettings: z.object({
            allowLocalAuthentication: z.boolean(),
            allowRegister: z.boolean(),
            allowExternalIdp: z.boolean(),
            disableLoginWithEmail: z.boolean(),
            disableLoginWithPhone: z.boolean(),
            hidePasswordReset: z.boolean(),
            ignoreUnknownUsernames: z.boolean(),
            passkeysAllowed: z.boolean(),
            secondFactors: z.array(z.enum([
                'otp',
                'u2f',
                'otp_email',
                'otp_sms',
                'recovery_codes'
            ])),
            defaultRedirectUri: z.string()
        }).nullable(),
        user: z.object({
            loginName: z.string(),
            displayName: z.string().optional()
        }).nullable(),
        authMethods: z.array(z.enum([
            'password',
            'passkey',
            'idp',
            'totp',
            'u2f',
            'otp_sms',
            'otp_email',
            'recovery_code'
        ])),
        params: z.string()
    })
});

export const zPostIdpStartBody = z.object({
    id: z.string().min(1),
    provider: z.enum([
        'github',
        'github_es',
        'gitlab',
        'gitlab_es',
        'apple',
        'google',
        'azure',
        'saml',
        'oauth',
        'oidc',
        'ldap',
        'jwt',
        'zitadel'
    ]),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    sessionId: z.string().optional(),
    postErrorRedirectUrl: z.string().optional(),
    loginHint: z.string().optional()
});

/**
 * IdP flow started
 */
export const zPostIdpStartResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('IdP flow started'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});

export const zPostIdpProcessBody = z.object({
    provider: z.string().min(1),
    id: z.string().min(1),
    token: z.string().min(1),
    requestId: z.string().optional(),
    organization: z.string().optional(),
    postErrorRedirectUrl: z.string().optional(),
    linkToSessionId: z.string().optional(),
    linkFingerprint: z.string().optional()
});

/**
 * IdP callback processed
 */
export const zPostIdpProcessResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('IdP callback processed'),
    data: z.object({
        redirect: z.string().optional(),
        samlData: z.object({
            url: z.string(),
            fields: z.record(z.string(), z.string())
        }).optional()
    })
});
