// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/settings/v2/branding_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceOwnerType } from "./settings_pb";
import { file_zitadel_settings_v2_settings } from "./settings_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/branding_settings.proto.
 */
export const file_zitadel_settings_v2_branding_settings: GenFile = /*@__PURE__*/
  fileDesc("Cit6aXRhZGVsL3NldHRpbmdzL3YyL2JyYW5kaW5nX3NldHRpbmdzLnByb3RvEhN6aXRhZGVsLnNldHRpbmdzLnYyIrkCChBCcmFuZGluZ1NldHRpbmdzEi8KC2xpZ2h0X3RoZW1lGAEgASgLMhoueml0YWRlbC5zZXR0aW5ncy52Mi5UaGVtZRIuCgpkYXJrX3RoZW1lGAIgASgLMhoueml0YWRlbC5zZXR0aW5ncy52Mi5UaGVtZRIQCghmb250X3VybBgDIAEoCRIeChZoaWRlX2xvZ2luX25hbWVfc3VmZml4GAQgASgIEhkKEWRpc2FibGVfd2F0ZXJtYXJrGAUgASgIEkMKE3Jlc291cmNlX293bmVyX3R5cGUYBiABKA4yJi56aXRhZGVsLnNldHRpbmdzLnYyLlJlc291cmNlT3duZXJUeXBlEjIKCnRoZW1lX21vZGUYByABKA4yHi56aXRhZGVsLnNldHRpbmdzLnYyLlRoZW1lTW9kZSKEAQoFVGhlbWUSFQoNcHJpbWFyeV9jb2xvchgBIAEoCRIYChBiYWNrZ3JvdW5kX2NvbG9yGAIgASgJEhIKCndhcm5fY29sb3IYAyABKAkSEgoKZm9udF9jb2xvchgEIAEoCRIQCghsb2dvX3VybBgFIAEoCRIQCghpY29uX3VybBgGIAEoCSpnCglUaGVtZU1vZGUSGgoWVEhFTUVfTU9ERV9VTlNQRUNJRklFRBAAEhMKD1RIRU1FX01PREVfQVVUTxABEhQKEFRIRU1FX01PREVfTElHSFQQAhITCg9USEVNRV9NT0RFX0RBUksQA2IGcHJvdG8z", [file_zitadel_settings_v2_settings]);

/**
 * @generated from message zitadel.settings.v2.BrandingSettings
 */
export type BrandingSettings = Message<"zitadel.settings.v2.BrandingSettings"> & {
  /**
   * @generated from field: zitadel.settings.v2.Theme light_theme = 1;
   */
  lightTheme?: Theme | undefined;

  /**
   * @generated from field: zitadel.settings.v2.Theme dark_theme = 2;
   */
  darkTheme?: Theme | undefined;

  /**
   * @generated from field: string font_url = 3;
   */
  fontUrl: string;

  /**
   * @generated from field: bool hide_login_name_suffix = 4;
   */
  hideLoginNameSuffix: boolean;

  /**
   * @generated from field: bool disable_watermark = 5;
   */
  disableWatermark: boolean;

  /**
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 6;
   */
  resourceOwnerType: ResourceOwnerType;

  /**
   * @generated from field: zitadel.settings.v2.ThemeMode theme_mode = 7;
   */
  themeMode: ThemeMode;
};

/**
 * Describes the message zitadel.settings.v2.BrandingSettings.
 * Use `create(BrandingSettingsSchema)` to create a new message.
 */
export const BrandingSettingsSchema: GenMessage<BrandingSettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_branding_settings, 0);

/**
 * @generated from message zitadel.settings.v2.Theme
 */
export type Theme = Message<"zitadel.settings.v2.Theme"> & {
  /**
   * @generated from field: string primary_color = 1;
   */
  primaryColor: string;

  /**
   * @generated from field: string background_color = 2;
   */
  backgroundColor: string;

  /**
   * @generated from field: string warn_color = 3;
   */
  warnColor: string;

  /**
   * @generated from field: string font_color = 4;
   */
  fontColor: string;

  /**
   * @generated from field: string logo_url = 5;
   */
  logoUrl: string;

  /**
   * @generated from field: string icon_url = 6;
   */
  iconUrl: string;
};

/**
 * Describes the message zitadel.settings.v2.Theme.
 * Use `create(ThemeSchema)` to create a new message.
 */
export const ThemeSchema: GenMessage<Theme> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_branding_settings, 1);

/**
 * @generated from enum zitadel.settings.v2.ThemeMode
 */
export enum ThemeMode {
  /**
   * @generated from enum value: THEME_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: THEME_MODE_AUTO = 1;
   */
  AUTO = 1,

  /**
   * @generated from enum value: THEME_MODE_LIGHT = 2;
   */
  LIGHT = 2,

  /**
   * @generated from enum value: THEME_MODE_DARK = 3;
   */
  DARK = 3,
}

/**
 * Describes the enum zitadel.settings.v2.ThemeMode.
 */
export const ThemeModeSchema: GenEnum<ThemeMode> = /*@__PURE__*/
  enumDesc(file_zitadel_settings_v2_branding_settings, 0);

