// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/settings/v2/domain_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceOwnerType } from "./settings_pb";
import { file_zitadel_settings_v2_settings } from "./settings_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/domain_settings.proto.
 */
export const file_zitadel_settings_v2_domain_settings: GenFile = /*@__PURE__*/
  fileDesc("Cil6aXRhZGVsL3NldHRpbmdzL3YyL2RvbWFpbl9zZXR0aW5ncy5wcm90bxITeml0YWRlbC5zZXR0aW5ncy52MiLXAQoORG9tYWluU2V0dGluZ3MSIgoabG9naW5fbmFtZV9pbmNsdWRlc19kb21haW4YASABKAgSJwofcmVxdWlyZV9vcmdfZG9tYWluX3ZlcmlmaWNhdGlvbhgCIAEoCBIzCitzbXRwX3NlbmRlcl9hZGRyZXNzX21hdGNoZXNfaW5zdGFuY2VfZG9tYWluGAMgASgIEkMKE3Jlc291cmNlX293bmVyX3R5cGUYBiABKA4yJi56aXRhZGVsLnNldHRpbmdzLnYyLlJlc291cmNlT3duZXJUeXBlYgZwcm90bzM", [file_zitadel_settings_v2_settings]);

/**
 * @generated from message zitadel.settings.v2.DomainSettings
 */
export type DomainSettings = Message<"zitadel.settings.v2.DomainSettings"> & {
  /**
   * @generated from field: bool login_name_includes_domain = 1;
   */
  loginNameIncludesDomain: boolean;

  /**
   * @generated from field: bool require_org_domain_verification = 2;
   */
  requireOrgDomainVerification: boolean;

  /**
   * @generated from field: bool smtp_sender_address_matches_instance_domain = 3;
   */
  smtpSenderAddressMatchesInstanceDomain: boolean;

  /**
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 6;
   */
  resourceOwnerType: ResourceOwnerType;
};

/**
 * Describes the message zitadel.settings.v2.DomainSettings.
 * Use `create(DomainSettingsSchema)` to create a new message.
 */
export const DomainSettingsSchema: GenMessage<DomainSettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_domain_settings, 0);

