// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/settings/v2/lockout_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceOwnerType } from "./settings_pb";
import { file_zitadel_settings_v2_settings } from "./settings_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/lockout_settings.proto.
 */
export const file_zitadel_settings_v2_lockout_settings: GenFile = /*@__PURE__*/
  fileDesc("Cip6aXRhZGVsL3NldHRpbmdzL3YyL2xvY2tvdXRfc2V0dGluZ3MucHJvdG8SE3ppdGFkZWwuc2V0dGluZ3MudjIijwEKD0xvY2tvdXRTZXR0aW5ncxIdChVtYXhfcGFzc3dvcmRfYXR0ZW1wdHMYASABKAQSQwoTcmVzb3VyY2Vfb3duZXJfdHlwZRgCIAEoDjImLnppdGFkZWwuc2V0dGluZ3MudjIuUmVzb3VyY2VPd25lclR5cGUSGAoQbWF4X290cF9hdHRlbXB0cxgDIAEoBGIGcHJvdG8z", [file_zitadel_settings_v2_settings]);

/**
 * @generated from message zitadel.settings.v2.LockoutSettings
 */
export type LockoutSettings = Message<"zitadel.settings.v2.LockoutSettings"> & {
  /**
   * @generated from field: uint64 max_password_attempts = 1;
   */
  maxPasswordAttempts: bigint;

  /**
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 2;
   */
  resourceOwnerType: ResourceOwnerType;

  /**
   * @generated from field: uint64 max_otp_attempts = 3;
   */
  maxOtpAttempts: bigint;
};

/**
 * Describes the message zitadel.settings.v2.LockoutSettings.
 * Use `create(LockoutSettingsSchema)` to create a new message.
 */
export const LockoutSettingsSchema: GenMessage<LockoutSettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_lockout_settings, 0);

