// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/settings/v2/password_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceOwnerType } from "./settings_pb";
import { file_zitadel_settings_v2_settings } from "./settings_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/password_settings.proto.
 */
export const file_zitadel_settings_v2_password_settings: GenFile = /*@__PURE__*/
  fileDesc("Cit6aXRhZGVsL3NldHRpbmdzL3YyL3Bhc3N3b3JkX3NldHRpbmdzLnByb3RvEhN6aXRhZGVsLnNldHRpbmdzLnYyIt8BChpQYXNzd29yZENvbXBsZXhpdHlTZXR0aW5ncxISCgptaW5fbGVuZ3RoGAEgASgEEhoKEnJlcXVpcmVzX3VwcGVyY2FzZRgCIAEoCBIaChJyZXF1aXJlc19sb3dlcmNhc2UYAyABKAgSFwoPcmVxdWlyZXNfbnVtYmVyGAQgASgIEhcKD3JlcXVpcmVzX3N5bWJvbBgFIAEoCBJDChNyZXNvdXJjZV9vd25lcl90eXBlGAYgASgOMiYueml0YWRlbC5zZXR0aW5ncy52Mi5SZXNvdXJjZU93bmVyVHlwZSKNAQoWUGFzc3dvcmRFeHBpcnlTZXR0aW5ncxIUCgxtYXhfYWdlX2RheXMYASABKAQSGAoQZXhwaXJlX3dhcm5fZGF5cxgCIAEoBBJDChNyZXNvdXJjZV9vd25lcl90eXBlGAMgASgOMiYueml0YWRlbC5zZXR0aW5ncy52Mi5SZXNvdXJjZU93bmVyVHlwZWIGcHJvdG8z", [file_zitadel_settings_v2_settings]);

/**
 * @generated from message zitadel.settings.v2.PasswordComplexitySettings
 */
export type PasswordComplexitySettings = Message<"zitadel.settings.v2.PasswordComplexitySettings"> & {
  /**
   * @generated from field: uint64 min_length = 1;
   */
  minLength: bigint;

  /**
   * @generated from field: bool requires_uppercase = 2;
   */
  requiresUppercase: boolean;

  /**
   * @generated from field: bool requires_lowercase = 3;
   */
  requiresLowercase: boolean;

  /**
   * @generated from field: bool requires_number = 4;
   */
  requiresNumber: boolean;

  /**
   * @generated from field: bool requires_symbol = 5;
   */
  requiresSymbol: boolean;

  /**
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 6;
   */
  resourceOwnerType: ResourceOwnerType;
};

/**
 * Describes the message zitadel.settings.v2.PasswordComplexitySettings.
 * Use `create(PasswordComplexitySettingsSchema)` to create a new message.
 */
export const PasswordComplexitySettingsSchema: GenMessage<PasswordComplexitySettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_password_settings, 0);

/**
 * @generated from message zitadel.settings.v2.PasswordExpirySettings
 */
export type PasswordExpirySettings = Message<"zitadel.settings.v2.PasswordExpirySettings"> & {
  /**
   * @generated from field: uint64 max_age_days = 1;
   */
  maxAgeDays: bigint;

  /**
   * @generated from field: uint64 expire_warn_days = 2;
   */
  expireWarnDays: bigint;

  /**
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 3;
   */
  resourceOwnerType: ResourceOwnerType;
};

/**
 * Describes the message zitadel.settings.v2.PasswordExpirySettings.
 * Use `create(PasswordExpirySettingsSchema)` to create a new message.
 */
export const PasswordExpirySettingsSchema: GenMessage<PasswordExpirySettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_password_settings, 1);

