// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/settings/v2/security_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/security_settings.proto.
 */
export const file_zitadel_settings_v2_security_settings: GenFile = /*@__PURE__*/
  fileDesc("Cit6aXRhZGVsL3NldHRpbmdzL3YyL3NlY3VyaXR5X3NldHRpbmdzLnByb3RvEhN6aXRhZGVsLnNldHRpbmdzLnYyItMBChBTZWN1cml0eVNldHRpbmdzEkQKD2VtYmVkZGVkX2lmcmFtZRgBIAEoCzIrLnppdGFkZWwuc2V0dGluZ3MudjIuRW1iZWRkZWRJZnJhbWVTZXR0aW5ncxIcChRlbmFibGVfaW1wZXJzb25hdGlvbhgCIAEoCBJbChtkeW5hbWljX2NsaWVudF9yZWdpc3RyYXRpb24YAyABKAsyNi56aXRhZGVsLnNldHRpbmdzLnYyLkR5bmFtaWNDbGllbnRSZWdpc3RyYXRpb25TZXR0aW5ncyJTCiFEeW5hbWljQ2xpZW50UmVnaXN0cmF0aW9uU2V0dGluZ3MSDwoHZW5hYmxlZBgBIAEoCBIdChVhbGxvd191bmF1dGhlbnRpY2F0ZWQYAiABKAgiQgoWRW1iZWRkZWRJZnJhbWVTZXR0aW5ncxIPCgdlbmFibGVkGAEgASgIEhcKD2FsbG93ZWRfb3JpZ2lucxgCIAMoCWIGcHJvdG8z");

/**
 * @generated from message zitadel.settings.v2.SecuritySettings
 */
export type SecuritySettings = Message<"zitadel.settings.v2.SecuritySettings"> & {
  /**
   * @generated from field: zitadel.settings.v2.EmbeddedIframeSettings embedded_iframe = 1;
   */
  embeddedIframe?: EmbeddedIframeSettings | undefined;

  /**
   * @generated from field: bool enable_impersonation = 2;
   */
  enableImpersonation: boolean;

  /**
   * @generated from field: zitadel.settings.v2.DynamicClientRegistrationSettings dynamic_client_registration = 3;
   */
  dynamicClientRegistration?: DynamicClientRegistrationSettings | undefined;
};

/**
 * Describes the message zitadel.settings.v2.SecuritySettings.
 * Use `create(SecuritySettingsSchema)` to create a new message.
 */
export const SecuritySettingsSchema: GenMessage<SecuritySettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_security_settings, 0);

/**
 * @generated from message zitadel.settings.v2.DynamicClientRegistrationSettings
 */
export type DynamicClientRegistrationSettings = Message<"zitadel.settings.v2.DynamicClientRegistrationSettings"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: bool allow_unauthenticated = 2;
   */
  allowUnauthenticated: boolean;
};

/**
 * Describes the message zitadel.settings.v2.DynamicClientRegistrationSettings.
 * Use `create(DynamicClientRegistrationSettingsSchema)` to create a new message.
 */
export const DynamicClientRegistrationSettingsSchema: GenMessage<DynamicClientRegistrationSettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_security_settings, 1);

/**
 * @generated from message zitadel.settings.v2.EmbeddedIframeSettings
 */
export type EmbeddedIframeSettings = Message<"zitadel.settings.v2.EmbeddedIframeSettings"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: repeated string allowed_origins = 2;
   */
  allowedOrigins: string[];
};

/**
 * Describes the message zitadel.settings.v2.EmbeddedIframeSettings.
 * Use `create(EmbeddedIframeSettingsSchema)` to create a new message.
 */
export const EmbeddedIframeSettingsSchema: GenMessage<EmbeddedIframeSettings> = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_security_settings, 2);

