// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/idp/v2/idp_service.proto (package zitadel.idp.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb";
import type { IDP } from "./idp_pb";
import { file_zitadel_idp_v2_idp } from "./idp_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/idp/v2/idp_service.proto.
 */
export const file_zitadel_idp_v2_idp_service: GenFile = /*@__PURE__*/
  fileDesc("CiB6aXRhZGVsL2lkcC92Mi9pZHBfc2VydmljZS5wcm90bxIOeml0YWRlbC5pZHAudjIiHwoRR2V0SURQQnlJRFJlcXVlc3QSCgoCaWQYASABKAkiNgoSR2V0SURQQnlJRFJlc3BvbnNlEiAKA2lkcBgBIAEoCzITLnppdGFkZWwuaWRwLnYyLklEUDJyChdJZGVudGl0eVByb3ZpZGVyU2VydmljZRJXCgpHZXRJRFBCeUlEEiEueml0YWRlbC5pZHAudjIuR2V0SURQQnlJRFJlcXVlc3QaIi56aXRhZGVsLmlkcC52Mi5HZXRJRFBCeUlEUmVzcG9uc2UoADAAYgZwcm90bzM", [file_zitadel_object_v2_object, file_zitadel_idp_v2_idp]);

/**
 * @generated from message zitadel.idp.v2.GetIDPByIDRequest
 */
export type GetIDPByIDRequest = Message<"zitadel.idp.v2.GetIDPByIDRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zitadel.idp.v2.GetIDPByIDRequest.
 * Use `create(GetIDPByIDRequestSchema)` to create a new message.
 */
export const GetIDPByIDRequestSchema: GenMessage<GetIDPByIDRequest> = /*@__PURE__*/
  messageDesc(file_zitadel_idp_v2_idp_service, 0);

/**
 * @generated from message zitadel.idp.v2.GetIDPByIDResponse
 */
export type GetIDPByIDResponse = Message<"zitadel.idp.v2.GetIDPByIDResponse"> & {
  /**
   * @generated from field: zitadel.idp.v2.IDP idp = 1;
   */
  idp?: IDP | undefined;
};

/**
 * Describes the message zitadel.idp.v2.GetIDPByIDResponse.
 * Use `create(GetIDPByIDResponseSchema)` to create a new message.
 */
export const GetIDPByIDResponseSchema: GenMessage<GetIDPByIDResponse> = /*@__PURE__*/
  messageDesc(file_zitadel_idp_v2_idp_service, 1);

/**
 * @generated from service zitadel.idp.v2.IdentityProviderService
 */
export const IdentityProviderService: GenService<{
  /**
   * @generated from rpc zitadel.idp.v2.IdentityProviderService.GetIDPByID
   */
  getIDPByID: {
    methodKind: "unary";
    input: typeof GetIDPByIDRequestSchema;
    output: typeof GetIDPByIDResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_zitadel_idp_v2_idp_service, 0);

