// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=none"
// @generated from file zitadel/metadata/v2/metadata.proto (package zitadel.metadata.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ByteFilterMethod, TextFilterMethod } from "../../filter/v2/filter_pb";
import { file_zitadel_filter_v2_filter } from "../../filter/v2/filter_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/metadata/v2/metadata.proto.
 */
export const file_zitadel_metadata_v2_metadata: GenFile = /*@__PURE__*/
  fileDesc("CiJ6aXRhZGVsL21ldGFkYXRhL3YyL21ldGFkYXRhLnByb3RvEhN6aXRhZGVsLm1ldGFkYXRhLnYyIooBCghNZXRhZGF0YRIxCg1jcmVhdGlvbl9kYXRlGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgtjaGFuZ2VfZGF0ZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASCwoDa2V5GAMgASgJEg0KBXZhbHVlGAQgASgMIl4KFE1ldGFkYXRhU2VhcmNoRmlsdGVyEjwKCmtleV9maWx0ZXIYASABKAsyJi56aXRhZGVsLm1ldGFkYXRhLnYyLk1ldGFkYXRhS2V5RmlsdGVySABCCAoGZmlsdGVyIlUKEU1ldGFkYXRhS2V5RmlsdGVyEgsKA2tleRgBIAEoCRIzCgZtZXRob2QYAiABKA4yIy56aXRhZGVsLmZpbHRlci52Mi5UZXh0RmlsdGVyTWV0aG9kIlkKE01ldGFkYXRhVmFsdWVGaWx0ZXISDQoFdmFsdWUYASABKAwSMwoGbWV0aG9kGAIgASgOMiMueml0YWRlbC5maWx0ZXIudjIuQnl0ZUZpbHRlck1ldGhvZGIGcHJvdG8z", [file_zitadel_filter_v2_filter, file_google_protobuf_timestamp]);

/**
 * @generated from message zitadel.metadata.v2.Metadata
 */
export type Metadata = Message<"zitadel.metadata.v2.Metadata"> & {
  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 1;
   */
  creationDate?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: Timestamp | undefined;

  /**
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * @generated from field: bytes value = 4;
   */
  value: Uint8Array;
};

/**
 * Describes the message zitadel.metadata.v2.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_zitadel_metadata_v2_metadata, 0);

/**
 * @generated from message zitadel.metadata.v2.MetadataSearchFilter
 */
export type MetadataSearchFilter = Message<"zitadel.metadata.v2.MetadataSearchFilter"> & {
  /**
   * @generated from oneof zitadel.metadata.v2.MetadataSearchFilter.filter
   */
  filter: {
    /**
     * @generated from field: zitadel.metadata.v2.MetadataKeyFilter key_filter = 1;
     */
    value: MetadataKeyFilter;
    case: "keyFilter";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message zitadel.metadata.v2.MetadataSearchFilter.
 * Use `create(MetadataSearchFilterSchema)` to create a new message.
 */
export const MetadataSearchFilterSchema: GenMessage<MetadataSearchFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_metadata_v2_metadata, 1);

/**
 * @generated from message zitadel.metadata.v2.MetadataKeyFilter
 */
export type MetadataKeyFilter = Message<"zitadel.metadata.v2.MetadataKeyFilter"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: zitadel.filter.v2.TextFilterMethod method = 2;
   */
  method: TextFilterMethod;
};

/**
 * Describes the message zitadel.metadata.v2.MetadataKeyFilter.
 * Use `create(MetadataKeyFilterSchema)` to create a new message.
 */
export const MetadataKeyFilterSchema: GenMessage<MetadataKeyFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_metadata_v2_metadata, 2);

/**
 * @generated from message zitadel.metadata.v2.MetadataValueFilter
 */
export type MetadataValueFilter = Message<"zitadel.metadata.v2.MetadataValueFilter"> & {
  /**
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;

  /**
   * @generated from field: zitadel.filter.v2.ByteFilterMethod method = 2;
   */
  method: ByteFilterMethod;
};

/**
 * Describes the message zitadel.metadata.v2.MetadataValueFilter.
 * Use `create(MetadataValueFilterSchema)` to create a new message.
 */
export const MetadataValueFilterSchema: GenMessage<MetadataValueFilter> = /*@__PURE__*/
  messageDesc(file_zitadel_metadata_v2_metadata, 3);

